#!/usr/bin/env python3
"""Generates a constexpr C++ header from a checkpoint.hpp-format text file.

Run at CMake configure time (like the git-SHA capture) so the resulting
binary needs zero runtime file I/O to get a working base dispatcher --
the weights are compiled in. Plain Python, not a compiled tool: avoids
the "build a tool to generate a header this same build needs" ordering
problem a C++ generator would hit at configure time.

Usage: embed_checkpoint.py <checkpoint_path> <output_header_path>
"""
import sys


def read_checkpoint(path):
    with open(path) as f:
        lines = f.read().splitlines()
    commit_sha = lines[0]
    rest = " ".join(lines[1:]).split()

    i = 0
    def next_int():
        nonlocal i
        v = int(rest[i])
        i += 1
        return v

    reg_size = next_int()
    for _ in range(reg_size):
        i += 1  # name
        i += 3  # global_index, in_size, out_size

    input_dim = next_int()
    hidden_dim = next_int()
    num_ops = next_int()

    def read_vec():
        nonlocal i
        n = next_int()
        vals = [float(v) for v in rest[i:i + n]]
        i += n
        return vals

    w1, b1, w2, b2 = read_vec(), read_vec(), read_vec(), read_vec()
    return commit_sha, input_dim, hidden_dim, num_ops, w1, b1, w2, b2


def emit(path_out, data):
    commit_sha, input_dim, hidden_dim, num_ops, w1, b1, w2, b2 = data

    def arr(name, vals):
        body = ", ".join(repr(v) for v in vals)
        return f"inline constexpr std::array<double, {len(vals)}> {name} = {{{body}}};"

    with open(path_out, "w") as f:
        f.write("#pragma once\n")
        f.write("// Generated by rsc/tools/embed_checkpoint.py at CMake configure time --\n")
        f.write("// do not edit, edit the checkpoint + re-run cmake instead.\n\n")
        f.write("#define SPATIUM_HAS_EMBEDDED_BASE 1\n\n")
        f.write("#include <array>\n#include <cstddef>\n\n")
        f.write("namespace rsc {\n\n")
        f.write(f'inline constexpr const char* kEmbeddedBaseCommitSha = "{commit_sha}";\n')
        f.write(f"inline constexpr std::size_t kEmbeddedBaseInputDim = {input_dim};\n")
        f.write(f"inline constexpr std::size_t kEmbeddedBaseHiddenDim = {hidden_dim};\n")
        f.write(f"inline constexpr std::size_t kEmbeddedBaseNumOps = {num_ops};\n\n")
        f.write(arr("kEmbeddedBaseW1", w1) + "\n")
        f.write(arr("kEmbeddedBaseB1", b1) + "\n")
        f.write(arr("kEmbeddedBaseW2", w2) + "\n")
        f.write(arr("kEmbeddedBaseB2", b2) + "\n\n")
        f.write("} // namespace rsc\n")


def emit_stub(path_out):
    with open(path_out, "w") as f:
        f.write("#pragma once\n")
        f.write("// No base checkpoint found at configure time -- run rsc/tools/train_base\n")
        f.write("// then re-run cmake to populate this header for real.\n\n")
        f.write("#define SPATIUM_HAS_EMBEDDED_BASE 0\n")


if __name__ == "__main__":
    if len(sys.argv) != 3:
        print("usage: embed_checkpoint.py <checkpoint_path> <output_header_path>", file=sys.stderr)
        sys.exit(1)
    emit(sys.argv[2], read_checkpoint(sys.argv[1]))
