#pragma once

// The toy action space both search experiments run on, factored out so
// they share one polygon rather than two that drift.
//
// Synthetic on purpose. Five integer operations mean the shortest chain is
// computable by breadth-first search, so "did it find the optimum" and
// "how many nodes did that cost" are facts rather than judgements.
// Borrowing Spatium's own registry would make the numbers prettier and
// every conclusion weaker.

#include <dispatcher.hpp>

#include <algorithm>
#include <cmath>
#include <cstdint>
#include <deque>
#include <map>
#include <random>
#include <vector>

namespace toy {


// Five integer actions. Two grow multiplicatively and three additively, so
// reaching a target usually needs both kinds -- a policy that learns only
// "add until close" cannot do better than chance on most problems.
constexpr int kNumActions = 5;

long long apply_action(long long state, int a) {
    switch (a) {
        case 0: return state + 1;
        case 1: return state + 3;
        case 2: return state - 2;
        case 3: return state * 2;
        case 4: return state * 3;
    }
    return state;
}

constexpr long long kStateLimit = 100000;   // an episode that leaves this has failed

struct Problem {
    long long start;
    long long target;
    std::size_t optimal;   // shortest action count, by breadth-first search
};

// The true optimum, so "how close to shortest" is measured rather than
// assumed. Bounded by depth and by |state|, which is what keeps this from
// exploring the whole integer line.
std::size_t shortest_path(long long start, long long target, std::size_t max_depth) {
    if (start == target) return 0;
    std::map<long long, std::size_t> seen{{start, 0}};
    std::deque<long long> queue{start};
    while (!queue.empty()) {
        const long long s = queue.front();
        queue.pop_front();
        const std::size_t d = seen[s];
        if (d >= max_depth) continue;
        for (int a = 0; a < kNumActions; ++a) {
            const long long n = apply_action(s, a);
            if (std::llabs(n) > kStateLimit) continue;
            if (seen.contains(n)) continue;
            if (n == target) return d + 1;
            seen[n] = d + 1;
            queue.push_back(n);
        }
    }
    return max_depth + 1;   // unreachable within the budget
}

// Targets are generated by walking, so every problem is solvable by
// construction; the walk length is an upper bound on the optimum and the
// BFS above finds the real one, which is often shorter.
Problem sample_problem(std::mt19937_64& rng, std::size_t walk) {
    std::uniform_int_distribution<int> start_dist(1, 20);
    std::uniform_int_distribution<int> action_dist(0, kNumActions - 1);
    for (;;) {
        Problem p{};
        p.start = start_dist(rng);
        long long s = p.start;
        bool ok = true;
        for (std::size_t i = 0; i < walk; ++i) {
            s = apply_action(s, action_dist(rng));
            if (std::llabs(s) > kStateLimit) { ok = false; break; }
        }
        if (!ok || s == p.start) continue;
        p.target = s;
        p.optimal = shortest_path(p.start, p.target, walk);
        if (p.optimal > walk) continue;   // BFS budget exhausted; discard rather than guess
        return p;
    }
}

// What the policy sees. The raw magnitudes span several orders, so each
// feature is compressed -- an unnormalised input makes the first layer's
// job about scale rather than about the relationship, which would confound
// exactly the capacity question being asked.
std::vector<double> features(long long state, long long target) {
    const auto squash = [](double v) { return std::tanh(v / 8.0); };
    const double s = static_cast<double>(state);
    const double t = static_cast<double>(target);
    const double diff = t - s;
    const double ratio = (std::abs(s) > 1e-9) ? t / s : 0.0;
    return {squash(s),
            squash(t),
            squash(diff),
            std::tanh(ratio / 4.0),
            std::tanh(std::log(std::abs(diff) + 1.0) / 4.0),
            1.0};
}

struct Episode {
    std::vector<rsc::ForwardCache> caches;
    std::vector<int> actions;
    bool solved = false;
    std::size_t length = 0;
};

// One free-running rollout. `greedy` picks the argmax (evaluation);
// otherwise the action is sampled, which is what makes the gradient an
// estimate of the policy gradient rather than of nothing.
Episode rollout(const rsc::Dispatcher& model, const Problem& p, std::size_t max_steps,
                std::mt19937_64& rng, bool greedy) {
    Episode ep;
    long long s = p.start;
    for (std::size_t step = 0; step < max_steps; ++step) {
        if (s == p.target) break;
        auto cache = model.forward_cached(features(s, p.target));
        auto probs = rsc::softmax(cache.logits);

        int a = 0;
        if (greedy) {
            a = static_cast<int>(std::max_element(probs.begin(), probs.end()) - probs.begin());
        } else {
            std::uniform_real_distribution<double> u(0.0, 1.0);
            double r = u(rng), acc = 0.0;
            for (int k = 0; k < kNumActions; ++k) {
                acc += probs[static_cast<std::size_t>(k)];
                if (r <= acc) { a = k; break; }
            }
        }

        ep.caches.push_back(std::move(cache));
        ep.actions.push_back(a);
        s = apply_action(s, a);
        ++ep.length;
        if (std::llabs(s) > kStateLimit) break;
    }
    ep.solved = (s == p.target);
    return ep;
}

struct Result {
    double success = 0.0;
    double optimal_rate = 0.0;   // share of solved episodes that were shortest
};

Result evaluate(const rsc::Dispatcher& model, std::size_t walk, std::size_t trials,
                std::uint64_t seed) {
    std::mt19937_64 rng(seed);
    std::size_t solved = 0, optimal = 0;
    for (std::size_t i = 0; i < trials; ++i) {
        const Problem p = sample_problem(rng, walk);
        const Episode ep = rollout(model, p, walk + 2, rng, /*greedy=*/true);
        if (ep.solved) {
            ++solved;
            if (ep.length <= p.optimal) ++optimal;
        }
    }
    Result r;
    r.success = static_cast<double>(solved) / static_cast<double>(trials);
    r.optimal_rate = solved ? static_cast<double>(optimal) / static_cast<double>(solved) : 0.0;
    return r;
}

// REINFORCE with a terminal reward and a running baseline, averaged over a
// batch before the weights move. The batch is not a detail: chain.hpp
// records that single-sample updates left accuracy stuck at chance over
// 20k steps on a task this one is strictly harder than.
void train(rsc::Dispatcher& model, std::size_t walk, std::size_t episodes, double lr,
           std::size_t batch, std::uint64_t seed) {
    std::mt19937_64 rng(seed);
    double baseline = 0.0;
    const std::size_t max_steps = walk + 2;

    for (std::size_t e = 0; e < episodes; e += batch) {
        rsc::Gradients sum;
        std::size_t contributing = 0;

        for (std::size_t b = 0; b < batch; ++b) {
            const Problem p = sample_problem(rng, walk);
            Episode ep = rollout(model, p, max_steps, rng, /*greedy=*/false);
            if (ep.caches.empty()) continue;

            // Solving is worth far more than saving a step, so the step
            // cost stays small: a policy that learns to stop trying in
            // order to avoid the penalty is the failure mode here.
            const double reward = (ep.solved ? 1.0 : 0.0) -
                                  0.02 * static_cast<double>(ep.length);
            const double advantage = reward - baseline;
            baseline += 0.01 * (reward - baseline);

            for (std::size_t i = 0; i < ep.caches.size(); ++i) {
                auto probs = rsc::softmax(ep.caches[i].logits);
                std::vector<double> dlogits(probs.size());
                for (std::size_t k = 0; k < probs.size(); ++k) dlogits[k] = probs[k];
                dlogits[static_cast<std::size_t>(ep.actions[i])] -= 1.0;
                for (auto& d : dlogits) d *= advantage;

                auto g = model.backward(ep.caches[i], dlogits);
                if (sum.dw1.empty()) {
                    sum = std::move(g);
                } else {
                    for (std::size_t j = 0; j < sum.dw1.size(); ++j) sum.dw1[j] += g.dw1[j];
                    for (std::size_t j = 0; j < sum.db1.size(); ++j) sum.db1[j] += g.db1[j];
                    for (std::size_t j = 0; j < sum.dw2.size(); ++j) sum.dw2[j] += g.dw2[j];
                    for (std::size_t j = 0; j < sum.db2.size(); ++j) sum.db2[j] += g.db2[j];
                }
                ++contributing;
            }
        }

        if (!contributing || sum.dw1.empty()) continue;
        const double scale = 1.0 / static_cast<double>(contributing);
        for (auto& v : sum.dw1) v *= scale;
        for (auto& v : sum.db1) v *= scale;
        for (auto& v : sum.dw2) v *= scale;
        for (auto& v : sum.db2) v *= scale;
        model.apply_gradients(sum, lr);
    }
}


}  // namespace toy
