#pragma once
// Generated by scripts/gen_connectivity.py -- do not edit; rerun it.
// The cells that compile, and the level each reached, for
// tests/test_connectivity.cpp. X(scalar type, scalar name, space, probe, level).
#define CONNECTIVITY_CELLS(X) \
    X(spatium::Dual<double>, "Dual", CylinderADL, Derivative, 3) \
    X(spatium::Dual<double>, "Dual", CylinderADL, DerivedDistance, 3) \
    X(spatium::Dual<double>, "Dual", CylinderADL, ExpLog, 3) \
    X(spatium::Dual<double>, "Dual", CylinderADL, FrechetMean, 3) \
    X(spatium::Dual<double>, "Dual", CylinderADL, Infinity, 3) \
    X(spatium::Dual<double>, "Dual", CylinderADL, MetricAxioms, 3) \
    X(spatium::Dual<double>, "Dual", CylinderADL, Midpoint, 3) \
    X(spatium::Dual<double>, "Dual", CylinderADL, VerifyExpLog, 3) \
    X(spatium::Dual<double>, "Dual", CylxE3, Derivative, 3) \
    X(spatium::Dual<double>, "Dual", CylxE3, DerivedDistance, 3) \
    X(spatium::Dual<double>, "Dual", CylxE3, ExpLog, 3) \
    X(spatium::Dual<double>, "Dual", CylxE3, FrechetMean, 3) \
    X(spatium::Dual<double>, "Dual", CylxE3, Infinity, 3) \
    X(spatium::Dual<double>, "Dual", CylxE3, MetricAxioms, 3) \
    X(spatium::Dual<double>, "Dual", CylxE3, Midpoint, 3) \
    X(spatium::Dual<double>, "Dual", CylxE3, VerifyExpLog, 3) \
    X(spatium::Dual<double>, "Dual", E1, Derivative, 3) \
    X(spatium::Dual<double>, "Dual", E1, DerivedDistance, 3) \
    X(spatium::Dual<double>, "Dual", E1, ExpLog, 3) \
    X(spatium::Dual<double>, "Dual", E1, FrechetMean, 3) \
    X(spatium::Dual<double>, "Dual", E1, Infinity, 3) \
    X(spatium::Dual<double>, "Dual", E1, MetricAxioms, 3) \
    X(spatium::Dual<double>, "Dual", E1, Midpoint, 3) \
    X(spatium::Dual<double>, "Dual", E1, VerifyExpLog, 3) \
    X(spatium::Dual<double>, "Dual", E3, Derivative, 3) \
    X(spatium::Dual<double>, "Dual", E3, DerivedDistance, 3) \
    X(spatium::Dual<double>, "Dual", E3, ExpLog, 3) \
    X(spatium::Dual<double>, "Dual", E3, FrechetMean, 3) \
    X(spatium::Dual<double>, "Dual", E3, Infinity, 3) \
    X(spatium::Dual<double>, "Dual", E3, MetricAxioms, 3) \
    X(spatium::Dual<double>, "Dual", E3, Midpoint, 3) \
    X(spatium::Dual<double>, "Dual", E3, VerifyExpLog, 3) \
    X(spatium::Dual<double>, "Dual", E4, Derivative, 3) \
    X(spatium::Dual<double>, "Dual", E4, DerivedDistance, 3) \
    X(spatium::Dual<double>, "Dual", E4, ExpLog, 3) \
    X(spatium::Dual<double>, "Dual", E4, FrechetMean, 3) \
    X(spatium::Dual<double>, "Dual", E4, Infinity, 3) \
    X(spatium::Dual<double>, "Dual", E4, MetricAxioms, 3) \
    X(spatium::Dual<double>, "Dual", E4, Midpoint, 3) \
    X(spatium::Dual<double>, "Dual", E4, VerifyExpLog, 3) \
    X(spatium::Dual<double>, "Dual", E8, Derivative, 3) \
    X(spatium::Dual<double>, "Dual", E8, DerivedDistance, 3) \
    X(spatium::Dual<double>, "Dual", E8, ExpLog, 3) \
    X(spatium::Dual<double>, "Dual", E8, FrechetMean, 3) \
    X(spatium::Dual<double>, "Dual", E8, Infinity, 3) \
    X(spatium::Dual<double>, "Dual", E8, MetricAxioms, 3) \
    X(spatium::Dual<double>, "Dual", E8, Midpoint, 3) \
    X(spatium::Dual<double>, "Dual", E8, VerifyExpLog, 3) \
    X(spatium::Dual<double>, "Dual", H1, Derivative, 3) \
    X(spatium::Dual<double>, "Dual", H1, DerivedDistance, 3) \
    X(spatium::Dual<double>, "Dual", H1, ExpLog, 3) \
    X(spatium::Dual<double>, "Dual", H1, FrechetMean, 3) \
    X(spatium::Dual<double>, "Dual", H1, Infinity, 3) \
    X(spatium::Dual<double>, "Dual", H1, MetricAxioms, 3) \
    X(spatium::Dual<double>, "Dual", H1, Midpoint, 3) \
    X(spatium::Dual<double>, "Dual", H1, VerifyExpLog, 3) \
    X(spatium::Dual<double>, "Dual", H2, Derivative, 3) \
    X(spatium::Dual<double>, "Dual", H2, DerivedDistance, 3) \
    X(spatium::Dual<double>, "Dual", H2, ExpLog, 3) \
    X(spatium::Dual<double>, "Dual", H2, FrechetMean, 3) \
    X(spatium::Dual<double>, "Dual", H2, Infinity, 3) \
    X(spatium::Dual<double>, "Dual", H2, MetricAxioms, 3) \
    X(spatium::Dual<double>, "Dual", H2, Midpoint, 3) \
    X(spatium::Dual<double>, "Dual", H2, VerifyExpLog, 3) \
    X(spatium::Dual<double>, "Dual", H2Derived, Derivative, 3) \
    X(spatium::Dual<double>, "Dual", H2Derived, DerivedDistance, 3) \
    X(spatium::Dual<double>, "Dual", H2Derived, ExpLog, 3) \
    X(spatium::Dual<double>, "Dual", H2Derived, FrechetMean, 3) \
    X(spatium::Dual<double>, "Dual", H2Derived, Infinity, 3) \
    X(spatium::Dual<double>, "Dual", H2Derived, MetricAxioms, 3) \
    X(spatium::Dual<double>, "Dual", H2Derived, Midpoint, 3) \
    X(spatium::Dual<double>, "Dual", H2Derived, VerifyExpLog, 3) \
    X(spatium::Dual<double>, "Dual", H2DerivedxS2, Derivative, 3) \
    X(spatium::Dual<double>, "Dual", H2DerivedxS2, DerivedDistance, 3) \
    X(spatium::Dual<double>, "Dual", H2DerivedxS2, ExpLog, 3) \
    X(spatium::Dual<double>, "Dual", H2DerivedxS2, FrechetMean, 3) \
    X(spatium::Dual<double>, "Dual", H2DerivedxS2, Infinity, 3) \
    X(spatium::Dual<double>, "Dual", H2DerivedxS2, MetricAxioms, 3) \
    X(spatium::Dual<double>, "Dual", H2DerivedxS2, Midpoint, 3) \
    X(spatium::Dual<double>, "Dual", H2DerivedxS2, VerifyExpLog, 3) \
    X(spatium::Dual<double>, "Dual", H2xE3, Derivative, 3) \
    X(spatium::Dual<double>, "Dual", H2xE3, DerivedDistance, 3) \
    X(spatium::Dual<double>, "Dual", H2xE3, ExpLog, 3) \
    X(spatium::Dual<double>, "Dual", H2xE3, FrechetMean, 3) \
    X(spatium::Dual<double>, "Dual", H2xE3, Infinity, 3) \
    X(spatium::Dual<double>, "Dual", H2xE3, MetricAxioms, 3) \
    X(spatium::Dual<double>, "Dual", H2xE3, Midpoint, 3) \
    X(spatium::Dual<double>, "Dual", H2xE3, VerifyExpLog, 3) \
    X(spatium::Dual<double>, "Dual", H4, Derivative, 3) \
    X(spatium::Dual<double>, "Dual", H4, DerivedDistance, 3) \
    X(spatium::Dual<double>, "Dual", H4, ExpLog, 3) \
    X(spatium::Dual<double>, "Dual", H4, FrechetMean, 3) \
    X(spatium::Dual<double>, "Dual", H4, Infinity, 3) \
    X(spatium::Dual<double>, "Dual", H4, MetricAxioms, 3) \
    X(spatium::Dual<double>, "Dual", H4, Midpoint, 3) \
    X(spatium::Dual<double>, "Dual", H4, VerifyExpLog, 3) \
    X(spatium::Dual<double>, "Dual", H8, Derivative, 3) \
    X(spatium::Dual<double>, "Dual", H8, DerivedDistance, 3) \
    X(spatium::Dual<double>, "Dual", H8, ExpLog, 3) \
    X(spatium::Dual<double>, "Dual", H8, FrechetMean, 3) \
    X(spatium::Dual<double>, "Dual", H8, Infinity, 3) \
    X(spatium::Dual<double>, "Dual", H8, MetricAxioms, 3) \
    X(spatium::Dual<double>, "Dual", H8, Midpoint, 3) \
    X(spatium::Dual<double>, "Dual", H8, VerifyExpLog, 3) \
    X(spatium::Dual<double>, "Dual", S1, Derivative, 3) \
    X(spatium::Dual<double>, "Dual", S1, DerivedDistance, 3) \
    X(spatium::Dual<double>, "Dual", S1, ExpLog, 3) \
    X(spatium::Dual<double>, "Dual", S1, FrechetMean, 3) \
    X(spatium::Dual<double>, "Dual", S1, Infinity, 3) \
    X(spatium::Dual<double>, "Dual", S1, MetricAxioms, 3) \
    X(spatium::Dual<double>, "Dual", S1, Midpoint, 3) \
    X(spatium::Dual<double>, "Dual", S1, VerifyExpLog, 3) \
    X(spatium::Dual<double>, "Dual", S2, Derivative, 3) \
    X(spatium::Dual<double>, "Dual", S2, DerivedDistance, 3) \
    X(spatium::Dual<double>, "Dual", S2, ExpLog, 3) \
    X(spatium::Dual<double>, "Dual", S2, FrechetMean, 3) \
    X(spatium::Dual<double>, "Dual", S2, Infinity, 3) \
    X(spatium::Dual<double>, "Dual", S2, MetricAxioms, 3) \
    X(spatium::Dual<double>, "Dual", S2, Midpoint, 3) \
    X(spatium::Dual<double>, "Dual", S2, VerifyExpLog, 3) \
    X(spatium::Dual<double>, "Dual", S2Derived, Derivative, 3) \
    X(spatium::Dual<double>, "Dual", S2Derived, DerivedDistance, 3) \
    X(spatium::Dual<double>, "Dual", S2Derived, ExpLog, 3) \
    X(spatium::Dual<double>, "Dual", S2Derived, FrechetMean, 3) \
    X(spatium::Dual<double>, "Dual", S2Derived, Infinity, 3) \
    X(spatium::Dual<double>, "Dual", S2Derived, MetricAxioms, 3) \
    X(spatium::Dual<double>, "Dual", S2Derived, Midpoint, 3) \
    X(spatium::Dual<double>, "Dual", S2Derived, VerifyExpLog, 3) \
    X(spatium::Dual<double>, "Dual", S2xE1, Derivative, 3) \
    X(spatium::Dual<double>, "Dual", S2xE1, DerivedDistance, 3) \
    X(spatium::Dual<double>, "Dual", S2xE1, ExpLog, 3) \
    X(spatium::Dual<double>, "Dual", S2xE1, FrechetMean, 3) \
    X(spatium::Dual<double>, "Dual", S2xE1, Infinity, 3) \
    X(spatium::Dual<double>, "Dual", S2xE1, MetricAxioms, 3) \
    X(spatium::Dual<double>, "Dual", S2xE1, Midpoint, 3) \
    X(spatium::Dual<double>, "Dual", S2xE1, VerifyExpLog, 3) \
    X(spatium::Dual<double>, "Dual", S2xH2, Derivative, 3) \
    X(spatium::Dual<double>, "Dual", S2xH2, DerivedDistance, 3) \
    X(spatium::Dual<double>, "Dual", S2xH2, ExpLog, 3) \
    X(spatium::Dual<double>, "Dual", S2xH2, FrechetMean, 3) \
    X(spatium::Dual<double>, "Dual", S2xH2, Infinity, 3) \
    X(spatium::Dual<double>, "Dual", S2xH2, MetricAxioms, 3) \
    X(spatium::Dual<double>, "Dual", S2xH2, Midpoint, 3) \
    X(spatium::Dual<double>, "Dual", S2xH2, VerifyExpLog, 3) \
    X(spatium::Dual<double>, "Dual", S2xS2, Derivative, 3) \
    X(spatium::Dual<double>, "Dual", S2xS2, DerivedDistance, 3) \
    X(spatium::Dual<double>, "Dual", S2xS2, ExpLog, 3) \
    X(spatium::Dual<double>, "Dual", S2xS2, FrechetMean, 3) \
    X(spatium::Dual<double>, "Dual", S2xS2, Infinity, 3) \
    X(spatium::Dual<double>, "Dual", S2xS2, MetricAxioms, 3) \
    X(spatium::Dual<double>, "Dual", S2xS2, Midpoint, 3) \
    X(spatium::Dual<double>, "Dual", S2xS2, VerifyExpLog, 3) \
    X(spatium::Dual<double>, "Dual", S3, Derivative, 3) \
    X(spatium::Dual<double>, "Dual", S3, DerivedDistance, 3) \
    X(spatium::Dual<double>, "Dual", S3, ExpLog, 3) \
    X(spatium::Dual<double>, "Dual", S3, FrechetMean, 3) \
    X(spatium::Dual<double>, "Dual", S3, Infinity, 3) \
    X(spatium::Dual<double>, "Dual", S3, MetricAxioms, 3) \
    X(spatium::Dual<double>, "Dual", S3, Midpoint, 3) \
    X(spatium::Dual<double>, "Dual", S3, VerifyExpLog, 3) \
    X(spatium::Dual<double>, "Dual", S4, Derivative, 3) \
    X(spatium::Dual<double>, "Dual", S4, DerivedDistance, 3) \
    X(spatium::Dual<double>, "Dual", S4, ExpLog, 3) \
    X(spatium::Dual<double>, "Dual", S4, FrechetMean, 3) \
    X(spatium::Dual<double>, "Dual", S4, Infinity, 3) \
    X(spatium::Dual<double>, "Dual", S4, MetricAxioms, 3) \
    X(spatium::Dual<double>, "Dual", S4, Midpoint, 3) \
    X(spatium::Dual<double>, "Dual", S4, VerifyExpLog, 3) \
    X(spatium::Dual<double>, "Dual", S7, Derivative, 3) \
    X(spatium::Dual<double>, "Dual", S7, DerivedDistance, 3) \
    X(spatium::Dual<double>, "Dual", S7, ExpLog, 3) \
    X(spatium::Dual<double>, "Dual", S7, FrechetMean, 3) \
    X(spatium::Dual<double>, "Dual", S7, Infinity, 3) \
    X(spatium::Dual<double>, "Dual", S7, MetricAxioms, 3) \
    X(spatium::Dual<double>, "Dual", S7, Midpoint, 3) \
    X(spatium::Dual<double>, "Dual", S7, VerifyExpLog, 3) \
    X(spatium::Dual<double>, "Dual", SPDAff, DerivedDistance, 3) \
    X(spatium::Dual<double>, "Dual", SPDAff, ExpLog, 3) \
    X(spatium::Dual<double>, "Dual", SPDAff, FrechetMean, 3) \
    X(spatium::Dual<double>, "Dual", SPDAff, Infinity, 3) \
    X(spatium::Dual<double>, "Dual", SPDAff, MetricAxioms, 3) \
    X(spatium::Dual<double>, "Dual", SPDAff, Midpoint, 3) \
    X(spatium::Dual<double>, "Dual", SPDAff, VerifyExpLog, 3) \
    X(spatium::Dual<double>, "Dual", SPDAffxS2, DerivedDistance, 3) \
    X(spatium::Dual<double>, "Dual", SPDAffxS2, ExpLog, 3) \
    X(spatium::Dual<double>, "Dual", SPDAffxS2, FrechetMean, 3) \
    X(spatium::Dual<double>, "Dual", SPDAffxS2, Infinity, 3) \
    X(spatium::Dual<double>, "Dual", SPDAffxS2, MetricAxioms, 3) \
    X(spatium::Dual<double>, "Dual", SPDAffxS2, Midpoint, 3) \
    X(spatium::Dual<double>, "Dual", SPDAffxS2, VerifyExpLog, 3) \
    X(spatium::Dual<double>, "Dual", SPDLogE, Derivative, 3) \
    X(spatium::Dual<double>, "Dual", SPDLogE, DerivedDistance, 3) \
    X(spatium::Dual<double>, "Dual", SPDLogE, ExpLog, 3) \
    X(spatium::Dual<double>, "Dual", SPDLogE, FrechetMean, 3) \
    X(spatium::Dual<double>, "Dual", SPDLogE, Infinity, 3) \
    X(spatium::Dual<double>, "Dual", SPDLogE, MetricAxioms, 3) \
    X(spatium::Dual<double>, "Dual", SPDLogE, Midpoint, 3) \
    X(spatium::Dual<double>, "Dual", SPDLogE, VerifyExpLog, 3) \
    X(spatium::Dual<double>, "Dual", SPDLogExS2, Derivative, 3) \
    X(spatium::Dual<double>, "Dual", SPDLogExS2, DerivedDistance, 3) \
    X(spatium::Dual<double>, "Dual", SPDLogExS2, ExpLog, 3) \
    X(spatium::Dual<double>, "Dual", SPDLogExS2, FrechetMean, 3) \
    X(spatium::Dual<double>, "Dual", SPDLogExS2, Infinity, 3) \
    X(spatium::Dual<double>, "Dual", SPDLogExS2, MetricAxioms, 3) \
    X(spatium::Dual<double>, "Dual", SPDLogExS2, Midpoint, 3) \
    X(spatium::Dual<double>, "Dual", SPDLogExS2, VerifyExpLog, 3) \
    X(spatium::Dual<double>, "Dual", SphereLevelSet, Derivative, 3) \
    X(spatium::Dual<double>, "Dual", SphereLevelSet, DerivedDistance, 1) \
    X(spatium::Dual<double>, "Dual", SphereLevelSet, ExpLog, 1) \
    X(spatium::Dual<double>, "Dual", SphereLevelSet, FrechetMean, 3) \
    X(spatium::Dual<double>, "Dual", SphereLevelSet, Infinity, 3) \
    X(spatium::Dual<double>, "Dual", SphereLevelSet, MetricAxioms, 3) \
    X(spatium::Dual<double>, "Dual", SphereLevelSet, Midpoint, 1) \
    X(spatium::Dual<double>, "Dual", SphereLevelSet, VerifyExpLog, 1) \
    X(spatium::Dual<double>, "Dual", TorusChart, Derivative, 3) \
    X(spatium::Dual<double>, "Dual", TorusChart, DerivedDistance, 1) \
    X(spatium::Dual<double>, "Dual", TorusChart, ExpLog, 1) \
    X(spatium::Dual<double>, "Dual", TorusChart, FrechetMean, 1) \
    X(spatium::Dual<double>, "Dual", TorusChart, Infinity, 3) \
    X(spatium::Dual<double>, "Dual", TorusChart, MetricAxioms, 3) \
    X(spatium::Dual<double>, "Dual", TorusChart, Midpoint, 1) \
    X(spatium::Dual<double>, "Dual", TorusChart, VerifyExpLog, 1) \
    X(spatium::Dual<spatium::Dual<double>>, "Dual2", CylinderADL, Derivative, 3) \
    X(spatium::Dual<spatium::Dual<double>>, "Dual2", CylinderADL, DerivedDistance, 3) \
    X(spatium::Dual<spatium::Dual<double>>, "Dual2", CylinderADL, ExpLog, 3) \
    X(spatium::Dual<spatium::Dual<double>>, "Dual2", CylinderADL, FrechetMean, 3) \
    X(spatium::Dual<spatium::Dual<double>>, "Dual2", CylinderADL, Infinity, 3) \
    X(spatium::Dual<spatium::Dual<double>>, "Dual2", CylinderADL, MetricAxioms, 3) \
    X(spatium::Dual<spatium::Dual<double>>, "Dual2", CylinderADL, Midpoint, 3) \
    X(spatium::Dual<spatium::Dual<double>>, "Dual2", CylinderADL, VerifyExpLog, 3) \
    X(spatium::Dual<spatium::Dual<double>>, "Dual2", CylxE3, Derivative, 3) \
    X(spatium::Dual<spatium::Dual<double>>, "Dual2", CylxE3, DerivedDistance, 3) \
    X(spatium::Dual<spatium::Dual<double>>, "Dual2", CylxE3, ExpLog, 3) \
    X(spatium::Dual<spatium::Dual<double>>, "Dual2", CylxE3, FrechetMean, 3) \
    X(spatium::Dual<spatium::Dual<double>>, "Dual2", CylxE3, Infinity, 3) \
    X(spatium::Dual<spatium::Dual<double>>, "Dual2", CylxE3, MetricAxioms, 3) \
    X(spatium::Dual<spatium::Dual<double>>, "Dual2", CylxE3, Midpoint, 3) \
    X(spatium::Dual<spatium::Dual<double>>, "Dual2", CylxE3, VerifyExpLog, 3) \
    X(spatium::Dual<spatium::Dual<double>>, "Dual2", E3, Derivative, 3) \
    X(spatium::Dual<spatium::Dual<double>>, "Dual2", E3, DerivedDistance, 3) \
    X(spatium::Dual<spatium::Dual<double>>, "Dual2", E3, ExpLog, 3) \
    X(spatium::Dual<spatium::Dual<double>>, "Dual2", E3, FrechetMean, 3) \
    X(spatium::Dual<spatium::Dual<double>>, "Dual2", E3, Infinity, 3) \
    X(spatium::Dual<spatium::Dual<double>>, "Dual2", E3, MetricAxioms, 3) \
    X(spatium::Dual<spatium::Dual<double>>, "Dual2", E3, Midpoint, 3) \
    X(spatium::Dual<spatium::Dual<double>>, "Dual2", E3, VerifyExpLog, 3) \
    X(spatium::Dual<spatium::Dual<double>>, "Dual2", H2, Derivative, 3) \
    X(spatium::Dual<spatium::Dual<double>>, "Dual2", H2, DerivedDistance, 3) \
    X(spatium::Dual<spatium::Dual<double>>, "Dual2", H2, ExpLog, 3) \
    X(spatium::Dual<spatium::Dual<double>>, "Dual2", H2, FrechetMean, 3) \
    X(spatium::Dual<spatium::Dual<double>>, "Dual2", H2, Infinity, 3) \
    X(spatium::Dual<spatium::Dual<double>>, "Dual2", H2, MetricAxioms, 3) \
    X(spatium::Dual<spatium::Dual<double>>, "Dual2", H2, Midpoint, 3) \
    X(spatium::Dual<spatium::Dual<double>>, "Dual2", H2, VerifyExpLog, 3) \
    X(spatium::Dual<spatium::Dual<double>>, "Dual2", H2Derived, Derivative, 3) \
    X(spatium::Dual<spatium::Dual<double>>, "Dual2", H2Derived, DerivedDistance, 3) \
    X(spatium::Dual<spatium::Dual<double>>, "Dual2", H2Derived, ExpLog, 3) \
    X(spatium::Dual<spatium::Dual<double>>, "Dual2", H2Derived, FrechetMean, 3) \
    X(spatium::Dual<spatium::Dual<double>>, "Dual2", H2Derived, Infinity, 3) \
    X(spatium::Dual<spatium::Dual<double>>, "Dual2", H2Derived, MetricAxioms, 3) \
    X(spatium::Dual<spatium::Dual<double>>, "Dual2", H2Derived, Midpoint, 3) \
    X(spatium::Dual<spatium::Dual<double>>, "Dual2", H2Derived, VerifyExpLog, 3) \
    X(spatium::Dual<spatium::Dual<double>>, "Dual2", H2DerivedxS2, Derivative, 3) \
    X(spatium::Dual<spatium::Dual<double>>, "Dual2", H2DerivedxS2, DerivedDistance, 3) \
    X(spatium::Dual<spatium::Dual<double>>, "Dual2", H2DerivedxS2, ExpLog, 3) \
    X(spatium::Dual<spatium::Dual<double>>, "Dual2", H2DerivedxS2, FrechetMean, 3) \
    X(spatium::Dual<spatium::Dual<double>>, "Dual2", H2DerivedxS2, Infinity, 3) \
    X(spatium::Dual<spatium::Dual<double>>, "Dual2", H2DerivedxS2, MetricAxioms, 3) \
    X(spatium::Dual<spatium::Dual<double>>, "Dual2", H2DerivedxS2, Midpoint, 3) \
    X(spatium::Dual<spatium::Dual<double>>, "Dual2", H2DerivedxS2, VerifyExpLog, 3) \
    X(spatium::Dual<spatium::Dual<double>>, "Dual2", H2xE3, Derivative, 3) \
    X(spatium::Dual<spatium::Dual<double>>, "Dual2", H2xE3, DerivedDistance, 3) \
    X(spatium::Dual<spatium::Dual<double>>, "Dual2", H2xE3, ExpLog, 3) \
    X(spatium::Dual<spatium::Dual<double>>, "Dual2", H2xE3, FrechetMean, 3) \
    X(spatium::Dual<spatium::Dual<double>>, "Dual2", H2xE3, Infinity, 3) \
    X(spatium::Dual<spatium::Dual<double>>, "Dual2", H2xE3, MetricAxioms, 3) \
    X(spatium::Dual<spatium::Dual<double>>, "Dual2", H2xE3, Midpoint, 3) \
    X(spatium::Dual<spatium::Dual<double>>, "Dual2", H2xE3, VerifyExpLog, 3) \
    X(spatium::Dual<spatium::Dual<double>>, "Dual2", S2, Derivative, 3) \
    X(spatium::Dual<spatium::Dual<double>>, "Dual2", S2, DerivedDistance, 3) \
    X(spatium::Dual<spatium::Dual<double>>, "Dual2", S2, ExpLog, 3) \
    X(spatium::Dual<spatium::Dual<double>>, "Dual2", S2, FrechetMean, 3) \
    X(spatium::Dual<spatium::Dual<double>>, "Dual2", S2, Infinity, 3) \
    X(spatium::Dual<spatium::Dual<double>>, "Dual2", S2, MetricAxioms, 3) \
    X(spatium::Dual<spatium::Dual<double>>, "Dual2", S2, Midpoint, 3) \
    X(spatium::Dual<spatium::Dual<double>>, "Dual2", S2, VerifyExpLog, 3) \
    X(spatium::Dual<spatium::Dual<double>>, "Dual2", S2Derived, Derivative, 3) \
    X(spatium::Dual<spatium::Dual<double>>, "Dual2", S2Derived, DerivedDistance, 3) \
    X(spatium::Dual<spatium::Dual<double>>, "Dual2", S2Derived, ExpLog, 3) \
    X(spatium::Dual<spatium::Dual<double>>, "Dual2", S2Derived, FrechetMean, 3) \
    X(spatium::Dual<spatium::Dual<double>>, "Dual2", S2Derived, Infinity, 3) \
    X(spatium::Dual<spatium::Dual<double>>, "Dual2", S2Derived, MetricAxioms, 3) \
    X(spatium::Dual<spatium::Dual<double>>, "Dual2", S2Derived, Midpoint, 3) \
    X(spatium::Dual<spatium::Dual<double>>, "Dual2", S2Derived, VerifyExpLog, 3) \
    X(spatium::Dual<spatium::Dual<double>>, "Dual2", S2xE1, Derivative, 3) \
    X(spatium::Dual<spatium::Dual<double>>, "Dual2", S2xE1, DerivedDistance, 3) \
    X(spatium::Dual<spatium::Dual<double>>, "Dual2", S2xE1, ExpLog, 3) \
    X(spatium::Dual<spatium::Dual<double>>, "Dual2", S2xE1, FrechetMean, 3) \
    X(spatium::Dual<spatium::Dual<double>>, "Dual2", S2xE1, Infinity, 3) \
    X(spatium::Dual<spatium::Dual<double>>, "Dual2", S2xE1, MetricAxioms, 3) \
    X(spatium::Dual<spatium::Dual<double>>, "Dual2", S2xE1, Midpoint, 3) \
    X(spatium::Dual<spatium::Dual<double>>, "Dual2", S2xE1, VerifyExpLog, 3) \
    X(spatium::Dual<spatium::Dual<double>>, "Dual2", S2xH2, Derivative, 3) \
    X(spatium::Dual<spatium::Dual<double>>, "Dual2", S2xH2, DerivedDistance, 3) \
    X(spatium::Dual<spatium::Dual<double>>, "Dual2", S2xH2, ExpLog, 3) \
    X(spatium::Dual<spatium::Dual<double>>, "Dual2", S2xH2, FrechetMean, 3) \
    X(spatium::Dual<spatium::Dual<double>>, "Dual2", S2xH2, Infinity, 3) \
    X(spatium::Dual<spatium::Dual<double>>, "Dual2", S2xH2, MetricAxioms, 3) \
    X(spatium::Dual<spatium::Dual<double>>, "Dual2", S2xH2, Midpoint, 3) \
    X(spatium::Dual<spatium::Dual<double>>, "Dual2", S2xH2, VerifyExpLog, 3) \
    X(spatium::Dual<spatium::Dual<double>>, "Dual2", S2xS2, Derivative, 3) \
    X(spatium::Dual<spatium::Dual<double>>, "Dual2", S2xS2, DerivedDistance, 3) \
    X(spatium::Dual<spatium::Dual<double>>, "Dual2", S2xS2, ExpLog, 3) \
    X(spatium::Dual<spatium::Dual<double>>, "Dual2", S2xS2, FrechetMean, 3) \
    X(spatium::Dual<spatium::Dual<double>>, "Dual2", S2xS2, Infinity, 3) \
    X(spatium::Dual<spatium::Dual<double>>, "Dual2", S2xS2, MetricAxioms, 3) \
    X(spatium::Dual<spatium::Dual<double>>, "Dual2", S2xS2, Midpoint, 3) \
    X(spatium::Dual<spatium::Dual<double>>, "Dual2", S2xS2, VerifyExpLog, 3) \
    X(spatium::Dual<spatium::Dual<double>>, "Dual2", SPDAff, DerivedDistance, 3) \
    X(spatium::Dual<spatium::Dual<double>>, "Dual2", SPDAff, ExpLog, 3) \
    X(spatium::Dual<spatium::Dual<double>>, "Dual2", SPDAff, FrechetMean, 3) \
    X(spatium::Dual<spatium::Dual<double>>, "Dual2", SPDAff, Infinity, 3) \
    X(spatium::Dual<spatium::Dual<double>>, "Dual2", SPDAff, MetricAxioms, 3) \
    X(spatium::Dual<spatium::Dual<double>>, "Dual2", SPDAff, Midpoint, 3) \
    X(spatium::Dual<spatium::Dual<double>>, "Dual2", SPDAff, VerifyExpLog, 3) \
    X(spatium::Dual<spatium::Dual<double>>, "Dual2", SPDAffxS2, DerivedDistance, 3) \
    X(spatium::Dual<spatium::Dual<double>>, "Dual2", SPDAffxS2, ExpLog, 3) \
    X(spatium::Dual<spatium::Dual<double>>, "Dual2", SPDAffxS2, FrechetMean, 3) \
    X(spatium::Dual<spatium::Dual<double>>, "Dual2", SPDAffxS2, Infinity, 3) \
    X(spatium::Dual<spatium::Dual<double>>, "Dual2", SPDAffxS2, MetricAxioms, 3) \
    X(spatium::Dual<spatium::Dual<double>>, "Dual2", SPDAffxS2, Midpoint, 3) \
    X(spatium::Dual<spatium::Dual<double>>, "Dual2", SPDAffxS2, VerifyExpLog, 3) \
    X(spatium::Dual<spatium::Dual<double>>, "Dual2", SPDLogE, Derivative, 3) \
    X(spatium::Dual<spatium::Dual<double>>, "Dual2", SPDLogE, DerivedDistance, 3) \
    X(spatium::Dual<spatium::Dual<double>>, "Dual2", SPDLogE, ExpLog, 3) \
    X(spatium::Dual<spatium::Dual<double>>, "Dual2", SPDLogE, FrechetMean, 3) \
    X(spatium::Dual<spatium::Dual<double>>, "Dual2", SPDLogE, Infinity, 3) \
    X(spatium::Dual<spatium::Dual<double>>, "Dual2", SPDLogE, MetricAxioms, 3) \
    X(spatium::Dual<spatium::Dual<double>>, "Dual2", SPDLogE, Midpoint, 3) \
    X(spatium::Dual<spatium::Dual<double>>, "Dual2", SPDLogE, VerifyExpLog, 3) \
    X(spatium::Dual<spatium::Dual<double>>, "Dual2", SPDLogExS2, Derivative, 3) \
    X(spatium::Dual<spatium::Dual<double>>, "Dual2", SPDLogExS2, DerivedDistance, 3) \
    X(spatium::Dual<spatium::Dual<double>>, "Dual2", SPDLogExS2, ExpLog, 3) \
    X(spatium::Dual<spatium::Dual<double>>, "Dual2", SPDLogExS2, FrechetMean, 3) \
    X(spatium::Dual<spatium::Dual<double>>, "Dual2", SPDLogExS2, Infinity, 3) \
    X(spatium::Dual<spatium::Dual<double>>, "Dual2", SPDLogExS2, MetricAxioms, 3) \
    X(spatium::Dual<spatium::Dual<double>>, "Dual2", SPDLogExS2, Midpoint, 3) \
    X(spatium::Dual<spatium::Dual<double>>, "Dual2", SPDLogExS2, VerifyExpLog, 3) \
    X(spatium::Dual<spatium::Dual<double>>, "Dual2", SphereLevelSet, Derivative, 3) \
    X(spatium::Dual<spatium::Dual<double>>, "Dual2", SphereLevelSet, DerivedDistance, 1) \
    X(spatium::Dual<spatium::Dual<double>>, "Dual2", SphereLevelSet, ExpLog, 1) \
    X(spatium::Dual<spatium::Dual<double>>, "Dual2", SphereLevelSet, FrechetMean, 3) \
    X(spatium::Dual<spatium::Dual<double>>, "Dual2", SphereLevelSet, Infinity, 3) \
    X(spatium::Dual<spatium::Dual<double>>, "Dual2", SphereLevelSet, MetricAxioms, 3) \
    X(spatium::Dual<spatium::Dual<double>>, "Dual2", SphereLevelSet, Midpoint, 1) \
    X(spatium::Dual<spatium::Dual<double>>, "Dual2", SphereLevelSet, VerifyExpLog, 1) \
    X(spatium::Dual<spatium::Dual<double>>, "Dual2", TorusChart, Derivative, 3) \
    X(spatium::Dual<spatium::Dual<double>>, "Dual2", TorusChart, DerivedDistance, 1) \
    X(spatium::Dual<spatium::Dual<double>>, "Dual2", TorusChart, ExpLog, 1) \
    X(spatium::Dual<spatium::Dual<double>>, "Dual2", TorusChart, FrechetMean, 1) \
    X(spatium::Dual<spatium::Dual<double>>, "Dual2", TorusChart, Infinity, 3) \
    X(spatium::Dual<spatium::Dual<double>>, "Dual2", TorusChart, MetricAxioms, 3) \
    X(spatium::Dual<spatium::Dual<double>>, "Dual2", TorusChart, Midpoint, 1) \
    X(spatium::Dual<spatium::Dual<double>>, "Dual2", TorusChart, VerifyExpLog, 1) \
    X(double, "double", CylinderADL, Derivative, 3) \
    X(double, "double", CylinderADL, DerivedDistance, 3) \
    X(double, "double", CylinderADL, ExpLog, 3) \
    X(double, "double", CylinderADL, FrechetMean, 3) \
    X(double, "double", CylinderADL, Infinity, 3) \
    X(double, "double", CylinderADL, MetricAxioms, 3) \
    X(double, "double", CylinderADL, Midpoint, 3) \
    X(double, "double", CylinderADL, VerifyExpLog, 3) \
    X(double, "double", CylxE3, Derivative, 3) \
    X(double, "double", CylxE3, DerivedDistance, 3) \
    X(double, "double", CylxE3, ExpLog, 3) \
    X(double, "double", CylxE3, FrechetMean, 3) \
    X(double, "double", CylxE3, Infinity, 3) \
    X(double, "double", CylxE3, MetricAxioms, 3) \
    X(double, "double", CylxE3, Midpoint, 3) \
    X(double, "double", CylxE3, VerifyExpLog, 3) \
    X(double, "double", E1, Derivative, 3) \
    X(double, "double", E1, DerivedDistance, 3) \
    X(double, "double", E1, ExpLog, 3) \
    X(double, "double", E1, FrechetMean, 3) \
    X(double, "double", E1, Infinity, 3) \
    X(double, "double", E1, MetricAxioms, 3) \
    X(double, "double", E1, Midpoint, 3) \
    X(double, "double", E1, VerifyExpLog, 3) \
    X(double, "double", E3, Derivative, 3) \
    X(double, "double", E3, DerivedDistance, 3) \
    X(double, "double", E3, ExpLog, 3) \
    X(double, "double", E3, FrechetMean, 3) \
    X(double, "double", E3, Infinity, 3) \
    X(double, "double", E3, MetricAxioms, 3) \
    X(double, "double", E3, Midpoint, 3) \
    X(double, "double", E3, VerifyExpLog, 3) \
    X(double, "double", E4, Derivative, 3) \
    X(double, "double", E4, DerivedDistance, 3) \
    X(double, "double", E4, ExpLog, 3) \
    X(double, "double", E4, FrechetMean, 3) \
    X(double, "double", E4, Infinity, 3) \
    X(double, "double", E4, MetricAxioms, 3) \
    X(double, "double", E4, Midpoint, 3) \
    X(double, "double", E4, VerifyExpLog, 3) \
    X(double, "double", E8, Derivative, 3) \
    X(double, "double", E8, DerivedDistance, 3) \
    X(double, "double", E8, ExpLog, 3) \
    X(double, "double", E8, FrechetMean, 3) \
    X(double, "double", E8, Infinity, 3) \
    X(double, "double", E8, MetricAxioms, 3) \
    X(double, "double", E8, Midpoint, 3) \
    X(double, "double", E8, VerifyExpLog, 3) \
    X(double, "double", H1, Derivative, 3) \
    X(double, "double", H1, DerivedDistance, 3) \
    X(double, "double", H1, ExpLog, 3) \
    X(double, "double", H1, FrechetMean, 3) \
    X(double, "double", H1, Infinity, 3) \
    X(double, "double", H1, MetricAxioms, 3) \
    X(double, "double", H1, Midpoint, 3) \
    X(double, "double", H1, VerifyExpLog, 3) \
    X(double, "double", H2, Derivative, 3) \
    X(double, "double", H2, DerivedDistance, 3) \
    X(double, "double", H2, ExpLog, 3) \
    X(double, "double", H2, FrechetMean, 3) \
    X(double, "double", H2, Infinity, 3) \
    X(double, "double", H2, MetricAxioms, 3) \
    X(double, "double", H2, Midpoint, 3) \
    X(double, "double", H2, VerifyExpLog, 3) \
    X(double, "double", H2Derived, Derivative, 3) \
    X(double, "double", H2Derived, DerivedDistance, 3) \
    X(double, "double", H2Derived, ExpLog, 3) \
    X(double, "double", H2Derived, FrechetMean, 3) \
    X(double, "double", H2Derived, Infinity, 3) \
    X(double, "double", H2Derived, MetricAxioms, 3) \
    X(double, "double", H2Derived, Midpoint, 3) \
    X(double, "double", H2Derived, VerifyExpLog, 3) \
    X(double, "double", H2DerivedxS2, Derivative, 3) \
    X(double, "double", H2DerivedxS2, DerivedDistance, 3) \
    X(double, "double", H2DerivedxS2, ExpLog, 3) \
    X(double, "double", H2DerivedxS2, FrechetMean, 3) \
    X(double, "double", H2DerivedxS2, Infinity, 3) \
    X(double, "double", H2DerivedxS2, MetricAxioms, 3) \
    X(double, "double", H2DerivedxS2, Midpoint, 3) \
    X(double, "double", H2DerivedxS2, VerifyExpLog, 3) \
    X(double, "double", H2xE3, Derivative, 3) \
    X(double, "double", H2xE3, DerivedDistance, 3) \
    X(double, "double", H2xE3, ExpLog, 3) \
    X(double, "double", H2xE3, FrechetMean, 3) \
    X(double, "double", H2xE3, Infinity, 3) \
    X(double, "double", H2xE3, MetricAxioms, 3) \
    X(double, "double", H2xE3, Midpoint, 3) \
    X(double, "double", H2xE3, VerifyExpLog, 3) \
    X(double, "double", H4, Derivative, 3) \
    X(double, "double", H4, DerivedDistance, 3) \
    X(double, "double", H4, ExpLog, 3) \
    X(double, "double", H4, FrechetMean, 3) \
    X(double, "double", H4, Infinity, 3) \
    X(double, "double", H4, MetricAxioms, 3) \
    X(double, "double", H4, Midpoint, 3) \
    X(double, "double", H4, VerifyExpLog, 3) \
    X(double, "double", H8, Derivative, 3) \
    X(double, "double", H8, DerivedDistance, 3) \
    X(double, "double", H8, ExpLog, 3) \
    X(double, "double", H8, FrechetMean, 3) \
    X(double, "double", H8, Infinity, 3) \
    X(double, "double", H8, MetricAxioms, 3) \
    X(double, "double", H8, Midpoint, 3) \
    X(double, "double", H8, VerifyExpLog, 3) \
    X(double, "double", S1, Derivative, 3) \
    X(double, "double", S1, DerivedDistance, 3) \
    X(double, "double", S1, ExpLog, 3) \
    X(double, "double", S1, FrechetMean, 3) \
    X(double, "double", S1, Infinity, 3) \
    X(double, "double", S1, MetricAxioms, 3) \
    X(double, "double", S1, Midpoint, 3) \
    X(double, "double", S1, VerifyExpLog, 3) \
    X(double, "double", S2, Derivative, 3) \
    X(double, "double", S2, DerivedDistance, 3) \
    X(double, "double", S2, ExpLog, 3) \
    X(double, "double", S2, FrechetMean, 3) \
    X(double, "double", S2, Infinity, 3) \
    X(double, "double", S2, MetricAxioms, 3) \
    X(double, "double", S2, Midpoint, 3) \
    X(double, "double", S2, VerifyExpLog, 3) \
    X(double, "double", S2Derived, Derivative, 3) \
    X(double, "double", S2Derived, DerivedDistance, 3) \
    X(double, "double", S2Derived, ExpLog, 3) \
    X(double, "double", S2Derived, FrechetMean, 3) \
    X(double, "double", S2Derived, Infinity, 3) \
    X(double, "double", S2Derived, MetricAxioms, 3) \
    X(double, "double", S2Derived, Midpoint, 3) \
    X(double, "double", S2Derived, VerifyExpLog, 3) \
    X(double, "double", S2xE1, Derivative, 3) \
    X(double, "double", S2xE1, DerivedDistance, 3) \
    X(double, "double", S2xE1, ExpLog, 3) \
    X(double, "double", S2xE1, FrechetMean, 3) \
    X(double, "double", S2xE1, Infinity, 3) \
    X(double, "double", S2xE1, MetricAxioms, 3) \
    X(double, "double", S2xE1, Midpoint, 3) \
    X(double, "double", S2xE1, VerifyExpLog, 3) \
    X(double, "double", S2xH2, Derivative, 3) \
    X(double, "double", S2xH2, DerivedDistance, 3) \
    X(double, "double", S2xH2, ExpLog, 3) \
    X(double, "double", S2xH2, FrechetMean, 3) \
    X(double, "double", S2xH2, Infinity, 3) \
    X(double, "double", S2xH2, MetricAxioms, 3) \
    X(double, "double", S2xH2, Midpoint, 3) \
    X(double, "double", S2xH2, VerifyExpLog, 3) \
    X(double, "double", S2xS2, Derivative, 3) \
    X(double, "double", S2xS2, DerivedDistance, 3) \
    X(double, "double", S2xS2, ExpLog, 3) \
    X(double, "double", S2xS2, FrechetMean, 3) \
    X(double, "double", S2xS2, Infinity, 3) \
    X(double, "double", S2xS2, MetricAxioms, 3) \
    X(double, "double", S2xS2, Midpoint, 3) \
    X(double, "double", S2xS2, VerifyExpLog, 3) \
    X(double, "double", S3, Derivative, 3) \
    X(double, "double", S3, DerivedDistance, 3) \
    X(double, "double", S3, ExpLog, 3) \
    X(double, "double", S3, FrechetMean, 3) \
    X(double, "double", S3, Infinity, 3) \
    X(double, "double", S3, MetricAxioms, 3) \
    X(double, "double", S3, Midpoint, 3) \
    X(double, "double", S3, VerifyExpLog, 3) \
    X(double, "double", S4, Derivative, 3) \
    X(double, "double", S4, DerivedDistance, 3) \
    X(double, "double", S4, ExpLog, 3) \
    X(double, "double", S4, FrechetMean, 3) \
    X(double, "double", S4, Infinity, 3) \
    X(double, "double", S4, MetricAxioms, 3) \
    X(double, "double", S4, Midpoint, 3) \
    X(double, "double", S4, VerifyExpLog, 3) \
    X(double, "double", S7, Derivative, 3) \
    X(double, "double", S7, DerivedDistance, 3) \
    X(double, "double", S7, ExpLog, 3) \
    X(double, "double", S7, FrechetMean, 3) \
    X(double, "double", S7, Infinity, 3) \
    X(double, "double", S7, MetricAxioms, 3) \
    X(double, "double", S7, Midpoint, 3) \
    X(double, "double", S7, VerifyExpLog, 3) \
    X(double, "double", SPDAff, Derivative, 3) \
    X(double, "double", SPDAff, DerivedDistance, 3) \
    X(double, "double", SPDAff, ExpLog, 3) \
    X(double, "double", SPDAff, FrechetMean, 3) \
    X(double, "double", SPDAff, Infinity, 3) \
    X(double, "double", SPDAff, MetricAxioms, 3) \
    X(double, "double", SPDAff, Midpoint, 3) \
    X(double, "double", SPDAff, VerifyExpLog, 3) \
    X(double, "double", SPDAffxS2, Derivative, 3) \
    X(double, "double", SPDAffxS2, DerivedDistance, 3) \
    X(double, "double", SPDAffxS2, ExpLog, 3) \
    X(double, "double", SPDAffxS2, FrechetMean, 3) \
    X(double, "double", SPDAffxS2, Infinity, 3) \
    X(double, "double", SPDAffxS2, MetricAxioms, 3) \
    X(double, "double", SPDAffxS2, Midpoint, 3) \
    X(double, "double", SPDAffxS2, VerifyExpLog, 3) \
    X(double, "double", SPDLogE, Derivative, 3) \
    X(double, "double", SPDLogE, DerivedDistance, 3) \
    X(double, "double", SPDLogE, ExpLog, 3) \
    X(double, "double", SPDLogE, FrechetMean, 3) \
    X(double, "double", SPDLogE, Infinity, 3) \
    X(double, "double", SPDLogE, MetricAxioms, 3) \
    X(double, "double", SPDLogE, Midpoint, 3) \
    X(double, "double", SPDLogE, VerifyExpLog, 3) \
    X(double, "double", SPDLogExS2, Derivative, 3) \
    X(double, "double", SPDLogExS2, DerivedDistance, 3) \
    X(double, "double", SPDLogExS2, ExpLog, 3) \
    X(double, "double", SPDLogExS2, FrechetMean, 3) \
    X(double, "double", SPDLogExS2, Infinity, 3) \
    X(double, "double", SPDLogExS2, MetricAxioms, 3) \
    X(double, "double", SPDLogExS2, Midpoint, 3) \
    X(double, "double", SPDLogExS2, VerifyExpLog, 3) \
    X(double, "double", SphereLevelSet, Derivative, 3) \
    X(double, "double", SphereLevelSet, DerivedDistance, 1) \
    X(double, "double", SphereLevelSet, ExpLog, 1) \
    X(double, "double", SphereLevelSet, FrechetMean, 3) \
    X(double, "double", SphereLevelSet, Infinity, 3) \
    X(double, "double", SphereLevelSet, MetricAxioms, 3) \
    X(double, "double", SphereLevelSet, Midpoint, 1) \
    X(double, "double", SphereLevelSet, VerifyExpLog, 1) \
    X(double, "double", TorusChart, Derivative, 3) \
    X(double, "double", TorusChart, DerivedDistance, 1) \
    X(double, "double", TorusChart, ExpLog, 1) \
    X(double, "double", TorusChart, FrechetMean, 1) \
    X(double, "double", TorusChart, Infinity, 3) \
    X(double, "double", TorusChart, MetricAxioms, 3) \
    X(double, "double", TorusChart, Midpoint, 1) \
    X(double, "double", TorusChart, VerifyExpLog, 1) \
    X(float, "float", CylinderADL, Derivative, 3) \
    X(float, "float", CylinderADL, DerivedDistance, 3) \
    X(float, "float", CylinderADL, ExpLog, 3) \
    X(float, "float", CylinderADL, FrechetMean, 3) \
    X(float, "float", CylinderADL, Infinity, 3) \
    X(float, "float", CylinderADL, MetricAxioms, 3) \
    X(float, "float", CylinderADL, Midpoint, 3) \
    X(float, "float", CylinderADL, VerifyExpLog, 3) \
    X(float, "float", CylxE3, Derivative, 3) \
    X(float, "float", CylxE3, DerivedDistance, 3) \
    X(float, "float", CylxE3, ExpLog, 3) \
    X(float, "float", CylxE3, FrechetMean, 3) \
    X(float, "float", CylxE3, Infinity, 3) \
    X(float, "float", CylxE3, MetricAxioms, 3) \
    X(float, "float", CylxE3, Midpoint, 3) \
    X(float, "float", CylxE3, VerifyExpLog, 3) \
    X(float, "float", E3, Derivative, 3) \
    X(float, "float", E3, DerivedDistance, 3) \
    X(float, "float", E3, ExpLog, 3) \
    X(float, "float", E3, FrechetMean, 3) \
    X(float, "float", E3, Infinity, 3) \
    X(float, "float", E3, MetricAxioms, 3) \
    X(float, "float", E3, Midpoint, 3) \
    X(float, "float", E3, VerifyExpLog, 3) \
    X(float, "float", H2, Derivative, 3) \
    X(float, "float", H2, DerivedDistance, 3) \
    X(float, "float", H2, ExpLog, 3) \
    X(float, "float", H2, FrechetMean, 3) \
    X(float, "float", H2, Infinity, 3) \
    X(float, "float", H2, MetricAxioms, 3) \
    X(float, "float", H2, Midpoint, 3) \
    X(float, "float", H2, VerifyExpLog, 3) \
    X(float, "float", H2Derived, Derivative, 3) \
    X(float, "float", H2Derived, DerivedDistance, 3) \
    X(float, "float", H2Derived, ExpLog, 3) \
    X(float, "float", H2Derived, FrechetMean, 3) \
    X(float, "float", H2Derived, Infinity, 3) \
    X(float, "float", H2Derived, MetricAxioms, 3) \
    X(float, "float", H2Derived, Midpoint, 3) \
    X(float, "float", H2Derived, VerifyExpLog, 3) \
    X(float, "float", H2DerivedxS2, Derivative, 3) \
    X(float, "float", H2DerivedxS2, DerivedDistance, 3) \
    X(float, "float", H2DerivedxS2, ExpLog, 3) \
    X(float, "float", H2DerivedxS2, FrechetMean, 3) \
    X(float, "float", H2DerivedxS2, Infinity, 3) \
    X(float, "float", H2DerivedxS2, MetricAxioms, 3) \
    X(float, "float", H2DerivedxS2, Midpoint, 3) \
    X(float, "float", H2DerivedxS2, VerifyExpLog, 3) \
    X(float, "float", H2xE3, Derivative, 3) \
    X(float, "float", H2xE3, DerivedDistance, 3) \
    X(float, "float", H2xE3, ExpLog, 3) \
    X(float, "float", H2xE3, FrechetMean, 3) \
    X(float, "float", H2xE3, Infinity, 3) \
    X(float, "float", H2xE3, MetricAxioms, 3) \
    X(float, "float", H2xE3, Midpoint, 3) \
    X(float, "float", H2xE3, VerifyExpLog, 3) \
    X(float, "float", S2, Derivative, 3) \
    X(float, "float", S2, DerivedDistance, 3) \
    X(float, "float", S2, ExpLog, 3) \
    X(float, "float", S2, FrechetMean, 3) \
    X(float, "float", S2, Infinity, 3) \
    X(float, "float", S2, MetricAxioms, 3) \
    X(float, "float", S2, Midpoint, 3) \
    X(float, "float", S2, VerifyExpLog, 3) \
    X(float, "float", S2Derived, Derivative, 3) \
    X(float, "float", S2Derived, DerivedDistance, 3) \
    X(float, "float", S2Derived, ExpLog, 3) \
    X(float, "float", S2Derived, FrechetMean, 3) \
    X(float, "float", S2Derived, Infinity, 3) \
    X(float, "float", S2Derived, MetricAxioms, 3) \
    X(float, "float", S2Derived, Midpoint, 3) \
    X(float, "float", S2Derived, VerifyExpLog, 3) \
    X(float, "float", S2xE1, Derivative, 3) \
    X(float, "float", S2xE1, DerivedDistance, 3) \
    X(float, "float", S2xE1, ExpLog, 3) \
    X(float, "float", S2xE1, FrechetMean, 3) \
    X(float, "float", S2xE1, Infinity, 3) \
    X(float, "float", S2xE1, MetricAxioms, 3) \
    X(float, "float", S2xE1, Midpoint, 3) \
    X(float, "float", S2xE1, VerifyExpLog, 3) \
    X(float, "float", S2xH2, Derivative, 3) \
    X(float, "float", S2xH2, DerivedDistance, 3) \
    X(float, "float", S2xH2, ExpLog, 3) \
    X(float, "float", S2xH2, FrechetMean, 3) \
    X(float, "float", S2xH2, Infinity, 3) \
    X(float, "float", S2xH2, MetricAxioms, 3) \
    X(float, "float", S2xH2, Midpoint, 3) \
    X(float, "float", S2xH2, VerifyExpLog, 3) \
    X(float, "float", S2xS2, Derivative, 3) \
    X(float, "float", S2xS2, DerivedDistance, 3) \
    X(float, "float", S2xS2, ExpLog, 3) \
    X(float, "float", S2xS2, FrechetMean, 3) \
    X(float, "float", S2xS2, Infinity, 3) \
    X(float, "float", S2xS2, MetricAxioms, 3) \
    X(float, "float", S2xS2, Midpoint, 3) \
    X(float, "float", S2xS2, VerifyExpLog, 3) \
    X(float, "float", SPDAff, Derivative, 3) \
    X(float, "float", SPDAff, DerivedDistance, 3) \
    X(float, "float", SPDAff, ExpLog, 3) \
    X(float, "float", SPDAff, FrechetMean, 3) \
    X(float, "float", SPDAff, Infinity, 3) \
    X(float, "float", SPDAff, MetricAxioms, 3) \
    X(float, "float", SPDAff, Midpoint, 3) \
    X(float, "float", SPDAff, VerifyExpLog, 3) \
    X(float, "float", SPDAffxS2, Derivative, 3) \
    X(float, "float", SPDAffxS2, DerivedDistance, 3) \
    X(float, "float", SPDAffxS2, ExpLog, 3) \
    X(float, "float", SPDAffxS2, FrechetMean, 3) \
    X(float, "float", SPDAffxS2, Infinity, 3) \
    X(float, "float", SPDAffxS2, MetricAxioms, 3) \
    X(float, "float", SPDAffxS2, Midpoint, 3) \
    X(float, "float", SPDAffxS2, VerifyExpLog, 3) \
    X(float, "float", SPDLogE, Derivative, 3) \
    X(float, "float", SPDLogE, DerivedDistance, 3) \
    X(float, "float", SPDLogE, ExpLog, 3) \
    X(float, "float", SPDLogE, FrechetMean, 3) \
    X(float, "float", SPDLogE, Infinity, 3) \
    X(float, "float", SPDLogE, MetricAxioms, 3) \
    X(float, "float", SPDLogE, Midpoint, 3) \
    X(float, "float", SPDLogE, VerifyExpLog, 3) \
    X(float, "float", SPDLogExS2, Derivative, 3) \
    X(float, "float", SPDLogExS2, DerivedDistance, 3) \
    X(float, "float", SPDLogExS2, ExpLog, 3) \
    X(float, "float", SPDLogExS2, FrechetMean, 3) \
    X(float, "float", SPDLogExS2, Infinity, 3) \
    X(float, "float", SPDLogExS2, MetricAxioms, 3) \
    X(float, "float", SPDLogExS2, Midpoint, 3) \
    X(float, "float", SPDLogExS2, VerifyExpLog, 3) \
    X(float, "float", SphereLevelSet, Derivative, 3) \
    X(float, "float", SphereLevelSet, DerivedDistance, 1) \
    X(float, "float", SphereLevelSet, ExpLog, 1) \
    X(float, "float", SphereLevelSet, FrechetMean, 3) \
    X(float, "float", SphereLevelSet, Infinity, 3) \
    X(float, "float", SphereLevelSet, MetricAxioms, 3) \
    X(float, "float", SphereLevelSet, Midpoint, 1) \
    X(float, "float", SphereLevelSet, VerifyExpLog, 1) \
    X(float, "float", TorusChart, Derivative, 3) \
    X(float, "float", TorusChart, DerivedDistance, 3) \
    X(float, "float", TorusChart, ExpLog, 3) \
    X(float, "float", TorusChart, FrechetMean, 3) \
    X(float, "float", TorusChart, Infinity, 3) \
    X(float, "float", TorusChart, MetricAxioms, 3) \
    X(float, "float", TorusChart, Midpoint, 3) \
    X(float, "float", TorusChart, VerifyExpLog, 2) \
    X(long double, "long double", CylinderADL, Derivative, 3) \
    X(long double, "long double", CylinderADL, DerivedDistance, 3) \
    X(long double, "long double", CylinderADL, ExpLog, 3) \
    X(long double, "long double", CylinderADL, FrechetMean, 3) \
    X(long double, "long double", CylinderADL, Infinity, 3) \
    X(long double, "long double", CylinderADL, MetricAxioms, 3) \
    X(long double, "long double", CylinderADL, Midpoint, 3) \
    X(long double, "long double", CylinderADL, VerifyExpLog, 3) \
    X(long double, "long double", CylxE3, Derivative, 3) \
    X(long double, "long double", CylxE3, DerivedDistance, 3) \
    X(long double, "long double", CylxE3, ExpLog, 3) \
    X(long double, "long double", CylxE3, FrechetMean, 3) \
    X(long double, "long double", CylxE3, Infinity, 3) \
    X(long double, "long double", CylxE3, MetricAxioms, 3) \
    X(long double, "long double", CylxE3, Midpoint, 3) \
    X(long double, "long double", CylxE3, VerifyExpLog, 3) \
    X(long double, "long double", E3, Derivative, 3) \
    X(long double, "long double", E3, DerivedDistance, 3) \
    X(long double, "long double", E3, ExpLog, 3) \
    X(long double, "long double", E3, FrechetMean, 3) \
    X(long double, "long double", E3, Infinity, 3) \
    X(long double, "long double", E3, MetricAxioms, 3) \
    X(long double, "long double", E3, Midpoint, 3) \
    X(long double, "long double", E3, VerifyExpLog, 3) \
    X(long double, "long double", H2, Derivative, 3) \
    X(long double, "long double", H2, DerivedDistance, 3) \
    X(long double, "long double", H2, ExpLog, 3) \
    X(long double, "long double", H2, FrechetMean, 3) \
    X(long double, "long double", H2, Infinity, 3) \
    X(long double, "long double", H2, MetricAxioms, 3) \
    X(long double, "long double", H2, Midpoint, 3) \
    X(long double, "long double", H2, VerifyExpLog, 3) \
    X(long double, "long double", H2Derived, Derivative, 3) \
    X(long double, "long double", H2Derived, DerivedDistance, 3) \
    X(long double, "long double", H2Derived, ExpLog, 3) \
    X(long double, "long double", H2Derived, FrechetMean, 3) \
    X(long double, "long double", H2Derived, Infinity, 3) \
    X(long double, "long double", H2Derived, MetricAxioms, 3) \
    X(long double, "long double", H2Derived, Midpoint, 3) \
    X(long double, "long double", H2Derived, VerifyExpLog, 3) \
    X(long double, "long double", H2DerivedxS2, Derivative, 3) \
    X(long double, "long double", H2DerivedxS2, DerivedDistance, 3) \
    X(long double, "long double", H2DerivedxS2, ExpLog, 3) \
    X(long double, "long double", H2DerivedxS2, FrechetMean, 3) \
    X(long double, "long double", H2DerivedxS2, Infinity, 3) \
    X(long double, "long double", H2DerivedxS2, MetricAxioms, 3) \
    X(long double, "long double", H2DerivedxS2, Midpoint, 3) \
    X(long double, "long double", H2DerivedxS2, VerifyExpLog, 3) \
    X(long double, "long double", H2xE3, Derivative, 3) \
    X(long double, "long double", H2xE3, DerivedDistance, 3) \
    X(long double, "long double", H2xE3, ExpLog, 3) \
    X(long double, "long double", H2xE3, FrechetMean, 3) \
    X(long double, "long double", H2xE3, Infinity, 3) \
    X(long double, "long double", H2xE3, MetricAxioms, 3) \
    X(long double, "long double", H2xE3, Midpoint, 3) \
    X(long double, "long double", H2xE3, VerifyExpLog, 3) \
    X(long double, "long double", S2, Derivative, 3) \
    X(long double, "long double", S2, DerivedDistance, 3) \
    X(long double, "long double", S2, ExpLog, 3) \
    X(long double, "long double", S2, FrechetMean, 3) \
    X(long double, "long double", S2, Infinity, 3) \
    X(long double, "long double", S2, MetricAxioms, 3) \
    X(long double, "long double", S2, Midpoint, 3) \
    X(long double, "long double", S2, VerifyExpLog, 3) \
    X(long double, "long double", S2Derived, Derivative, 3) \
    X(long double, "long double", S2Derived, DerivedDistance, 3) \
    X(long double, "long double", S2Derived, ExpLog, 3) \
    X(long double, "long double", S2Derived, FrechetMean, 3) \
    X(long double, "long double", S2Derived, Infinity, 3) \
    X(long double, "long double", S2Derived, MetricAxioms, 3) \
    X(long double, "long double", S2Derived, Midpoint, 3) \
    X(long double, "long double", S2Derived, VerifyExpLog, 3) \
    X(long double, "long double", S2xE1, Derivative, 3) \
    X(long double, "long double", S2xE1, DerivedDistance, 3) \
    X(long double, "long double", S2xE1, ExpLog, 3) \
    X(long double, "long double", S2xE1, FrechetMean, 3) \
    X(long double, "long double", S2xE1, Infinity, 3) \
    X(long double, "long double", S2xE1, MetricAxioms, 3) \
    X(long double, "long double", S2xE1, Midpoint, 3) \
    X(long double, "long double", S2xE1, VerifyExpLog, 3) \
    X(long double, "long double", S2xH2, Derivative, 3) \
    X(long double, "long double", S2xH2, DerivedDistance, 3) \
    X(long double, "long double", S2xH2, ExpLog, 3) \
    X(long double, "long double", S2xH2, FrechetMean, 3) \
    X(long double, "long double", S2xH2, Infinity, 3) \
    X(long double, "long double", S2xH2, MetricAxioms, 3) \
    X(long double, "long double", S2xH2, Midpoint, 3) \
    X(long double, "long double", S2xH2, VerifyExpLog, 3) \
    X(long double, "long double", S2xS2, Derivative, 3) \
    X(long double, "long double", S2xS2, DerivedDistance, 3) \
    X(long double, "long double", S2xS2, ExpLog, 3) \
    X(long double, "long double", S2xS2, FrechetMean, 3) \
    X(long double, "long double", S2xS2, Infinity, 3) \
    X(long double, "long double", S2xS2, MetricAxioms, 3) \
    X(long double, "long double", S2xS2, Midpoint, 3) \
    X(long double, "long double", S2xS2, VerifyExpLog, 3) \
    X(long double, "long double", SPDAff, Derivative, 3) \
    X(long double, "long double", SPDAff, DerivedDistance, 3) \
    X(long double, "long double", SPDAff, ExpLog, 3) \
    X(long double, "long double", SPDAff, FrechetMean, 3) \
    X(long double, "long double", SPDAff, Infinity, 3) \
    X(long double, "long double", SPDAff, MetricAxioms, 3) \
    X(long double, "long double", SPDAff, Midpoint, 3) \
    X(long double, "long double", SPDAff, VerifyExpLog, 3) \
    X(long double, "long double", SPDAffxS2, Derivative, 3) \
    X(long double, "long double", SPDAffxS2, DerivedDistance, 3) \
    X(long double, "long double", SPDAffxS2, ExpLog, 3) \
    X(long double, "long double", SPDAffxS2, FrechetMean, 3) \
    X(long double, "long double", SPDAffxS2, Infinity, 3) \
    X(long double, "long double", SPDAffxS2, MetricAxioms, 3) \
    X(long double, "long double", SPDAffxS2, Midpoint, 3) \
    X(long double, "long double", SPDAffxS2, VerifyExpLog, 3) \
    X(long double, "long double", SPDLogE, Derivative, 3) \
    X(long double, "long double", SPDLogE, DerivedDistance, 3) \
    X(long double, "long double", SPDLogE, ExpLog, 3) \
    X(long double, "long double", SPDLogE, FrechetMean, 3) \
    X(long double, "long double", SPDLogE, Infinity, 3) \
    X(long double, "long double", SPDLogE, MetricAxioms, 3) \
    X(long double, "long double", SPDLogE, Midpoint, 3) \
    X(long double, "long double", SPDLogE, VerifyExpLog, 3) \
    X(long double, "long double", SPDLogExS2, Derivative, 3) \
    X(long double, "long double", SPDLogExS2, DerivedDistance, 3) \
    X(long double, "long double", SPDLogExS2, ExpLog, 3) \
    X(long double, "long double", SPDLogExS2, FrechetMean, 3) \
    X(long double, "long double", SPDLogExS2, Infinity, 3) \
    X(long double, "long double", SPDLogExS2, MetricAxioms, 3) \
    X(long double, "long double", SPDLogExS2, Midpoint, 3) \
    X(long double, "long double", SPDLogExS2, VerifyExpLog, 3) \
    X(long double, "long double", SphereLevelSet, Derivative, 3) \
    X(long double, "long double", SphereLevelSet, DerivedDistance, 1) \
    X(long double, "long double", SphereLevelSet, ExpLog, 1) \
    X(long double, "long double", SphereLevelSet, FrechetMean, 3) \
    X(long double, "long double", SphereLevelSet, Infinity, 3) \
    X(long double, "long double", SphereLevelSet, MetricAxioms, 3) \
    X(long double, "long double", SphereLevelSet, Midpoint, 1) \
    X(long double, "long double", SphereLevelSet, VerifyExpLog, 1) \
    X(long double, "long double", TorusChart, Derivative, 3) \
    X(long double, "long double", TorusChart, DerivedDistance, 1) \
    X(long double, "long double", TorusChart, ExpLog, 1) \
    X(long double, "long double", TorusChart, FrechetMean, 1) \
    X(long double, "long double", TorusChart, Infinity, 3) \
    X(long double, "long double", TorusChart, MetricAxioms, 3) \
    X(long double, "long double", TorusChart, Midpoint, 1) \
    X(long double, "long double", TorusChart, VerifyExpLog, 1) \
    CONNECTIVITY_CELLS_BOOST(X)

#if SPATIUM_HAS_BOOST_MULTIPRECISION
#define CONNECTIVITY_CELLS_BOOST(X) \
    X(spatium::Real50, "Real50", CylinderADL, Derivative, 3) \
    X(spatium::Real50, "Real50", CylinderADL, DerivedDistance, 3) \
    X(spatium::Real50, "Real50", CylinderADL, ExpLog, 3) \
    X(spatium::Real50, "Real50", CylinderADL, FrechetMean, 3) \
    X(spatium::Real50, "Real50", CylinderADL, Infinity, 3) \
    X(spatium::Real50, "Real50", CylinderADL, MetricAxioms, 3) \
    X(spatium::Real50, "Real50", CylinderADL, Midpoint, 3) \
    X(spatium::Real50, "Real50", CylinderADL, VerifyExpLog, 3) \
    X(spatium::Real50, "Real50", CylxE3, Derivative, 3) \
    X(spatium::Real50, "Real50", CylxE3, DerivedDistance, 3) \
    X(spatium::Real50, "Real50", CylxE3, ExpLog, 3) \
    X(spatium::Real50, "Real50", CylxE3, FrechetMean, 3) \
    X(spatium::Real50, "Real50", CylxE3, Infinity, 3) \
    X(spatium::Real50, "Real50", CylxE3, MetricAxioms, 3) \
    X(spatium::Real50, "Real50", CylxE3, Midpoint, 3) \
    X(spatium::Real50, "Real50", CylxE3, VerifyExpLog, 3) \
    X(spatium::Real50, "Real50", E1, Derivative, 3) \
    X(spatium::Real50, "Real50", E1, DerivedDistance, 3) \
    X(spatium::Real50, "Real50", E1, ExpLog, 3) \
    X(spatium::Real50, "Real50", E1, FrechetMean, 3) \
    X(spatium::Real50, "Real50", E1, Infinity, 3) \
    X(spatium::Real50, "Real50", E1, MetricAxioms, 3) \
    X(spatium::Real50, "Real50", E1, Midpoint, 3) \
    X(spatium::Real50, "Real50", E1, VerifyExpLog, 3) \
    X(spatium::Real50, "Real50", E3, Derivative, 3) \
    X(spatium::Real50, "Real50", E3, DerivedDistance, 3) \
    X(spatium::Real50, "Real50", E3, ExpLog, 3) \
    X(spatium::Real50, "Real50", E3, FrechetMean, 3) \
    X(spatium::Real50, "Real50", E3, Infinity, 3) \
    X(spatium::Real50, "Real50", E3, MetricAxioms, 3) \
    X(spatium::Real50, "Real50", E3, Midpoint, 3) \
    X(spatium::Real50, "Real50", E3, VerifyExpLog, 3) \
    X(spatium::Real50, "Real50", E4, Derivative, 3) \
    X(spatium::Real50, "Real50", E4, DerivedDistance, 3) \
    X(spatium::Real50, "Real50", E4, ExpLog, 3) \
    X(spatium::Real50, "Real50", E4, FrechetMean, 3) \
    X(spatium::Real50, "Real50", E4, Infinity, 3) \
    X(spatium::Real50, "Real50", E4, MetricAxioms, 3) \
    X(spatium::Real50, "Real50", E4, Midpoint, 3) \
    X(spatium::Real50, "Real50", E4, VerifyExpLog, 3) \
    X(spatium::Real50, "Real50", E8, Derivative, 3) \
    X(spatium::Real50, "Real50", E8, DerivedDistance, 3) \
    X(spatium::Real50, "Real50", E8, ExpLog, 3) \
    X(spatium::Real50, "Real50", E8, FrechetMean, 3) \
    X(spatium::Real50, "Real50", E8, Infinity, 3) \
    X(spatium::Real50, "Real50", E8, MetricAxioms, 3) \
    X(spatium::Real50, "Real50", E8, Midpoint, 3) \
    X(spatium::Real50, "Real50", E8, VerifyExpLog, 3) \
    X(spatium::Real50, "Real50", H1, Derivative, 3) \
    X(spatium::Real50, "Real50", H1, DerivedDistance, 3) \
    X(spatium::Real50, "Real50", H1, ExpLog, 3) \
    X(spatium::Real50, "Real50", H1, FrechetMean, 3) \
    X(spatium::Real50, "Real50", H1, Infinity, 3) \
    X(spatium::Real50, "Real50", H1, MetricAxioms, 3) \
    X(spatium::Real50, "Real50", H1, Midpoint, 3) \
    X(spatium::Real50, "Real50", H1, VerifyExpLog, 3) \
    X(spatium::Real50, "Real50", H2, Derivative, 3) \
    X(spatium::Real50, "Real50", H2, DerivedDistance, 3) \
    X(spatium::Real50, "Real50", H2, ExpLog, 3) \
    X(spatium::Real50, "Real50", H2, FrechetMean, 3) \
    X(spatium::Real50, "Real50", H2, Infinity, 3) \
    X(spatium::Real50, "Real50", H2, MetricAxioms, 3) \
    X(spatium::Real50, "Real50", H2, Midpoint, 3) \
    X(spatium::Real50, "Real50", H2, VerifyExpLog, 3) \
    X(spatium::Real50, "Real50", H2xE3, Derivative, 3) \
    X(spatium::Real50, "Real50", H2xE3, DerivedDistance, 3) \
    X(spatium::Real50, "Real50", H2xE3, ExpLog, 3) \
    X(spatium::Real50, "Real50", H2xE3, FrechetMean, 3) \
    X(spatium::Real50, "Real50", H2xE3, Infinity, 3) \
    X(spatium::Real50, "Real50", H2xE3, MetricAxioms, 3) \
    X(spatium::Real50, "Real50", H2xE3, Midpoint, 3) \
    X(spatium::Real50, "Real50", H2xE3, VerifyExpLog, 3) \
    X(spatium::Real50, "Real50", H4, Derivative, 3) \
    X(spatium::Real50, "Real50", H4, DerivedDistance, 3) \
    X(spatium::Real50, "Real50", H4, ExpLog, 3) \
    X(spatium::Real50, "Real50", H4, FrechetMean, 3) \
    X(spatium::Real50, "Real50", H4, Infinity, 3) \
    X(spatium::Real50, "Real50", H4, MetricAxioms, 3) \
    X(spatium::Real50, "Real50", H4, Midpoint, 3) \
    X(spatium::Real50, "Real50", H4, VerifyExpLog, 3) \
    X(spatium::Real50, "Real50", H8, Derivative, 3) \
    X(spatium::Real50, "Real50", H8, DerivedDistance, 3) \
    X(spatium::Real50, "Real50", H8, ExpLog, 3) \
    X(spatium::Real50, "Real50", H8, FrechetMean, 3) \
    X(spatium::Real50, "Real50", H8, Infinity, 3) \
    X(spatium::Real50, "Real50", H8, MetricAxioms, 3) \
    X(spatium::Real50, "Real50", H8, Midpoint, 3) \
    X(spatium::Real50, "Real50", H8, VerifyExpLog, 3) \
    X(spatium::Real50, "Real50", S1, Derivative, 3) \
    X(spatium::Real50, "Real50", S1, DerivedDistance, 3) \
    X(spatium::Real50, "Real50", S1, ExpLog, 3) \
    X(spatium::Real50, "Real50", S1, FrechetMean, 3) \
    X(spatium::Real50, "Real50", S1, Infinity, 3) \
    X(spatium::Real50, "Real50", S1, MetricAxioms, 3) \
    X(spatium::Real50, "Real50", S1, Midpoint, 3) \
    X(spatium::Real50, "Real50", S1, VerifyExpLog, 3) \
    X(spatium::Real50, "Real50", S2, Derivative, 3) \
    X(spatium::Real50, "Real50", S2, DerivedDistance, 3) \
    X(spatium::Real50, "Real50", S2, ExpLog, 3) \
    X(spatium::Real50, "Real50", S2, FrechetMean, 3) \
    X(spatium::Real50, "Real50", S2, Infinity, 3) \
    X(spatium::Real50, "Real50", S2, MetricAxioms, 3) \
    X(spatium::Real50, "Real50", S2, Midpoint, 3) \
    X(spatium::Real50, "Real50", S2, VerifyExpLog, 3) \
    X(spatium::Real50, "Real50", S2xE1, Derivative, 3) \
    X(spatium::Real50, "Real50", S2xE1, DerivedDistance, 3) \
    X(spatium::Real50, "Real50", S2xE1, ExpLog, 3) \
    X(spatium::Real50, "Real50", S2xE1, FrechetMean, 3) \
    X(spatium::Real50, "Real50", S2xE1, Infinity, 3) \
    X(spatium::Real50, "Real50", S2xE1, MetricAxioms, 3) \
    X(spatium::Real50, "Real50", S2xE1, Midpoint, 3) \
    X(spatium::Real50, "Real50", S2xE1, VerifyExpLog, 3) \
    X(spatium::Real50, "Real50", S2xH2, Derivative, 3) \
    X(spatium::Real50, "Real50", S2xH2, DerivedDistance, 3) \
    X(spatium::Real50, "Real50", S2xH2, ExpLog, 3) \
    X(spatium::Real50, "Real50", S2xH2, FrechetMean, 3) \
    X(spatium::Real50, "Real50", S2xH2, Infinity, 3) \
    X(spatium::Real50, "Real50", S2xH2, MetricAxioms, 3) \
    X(spatium::Real50, "Real50", S2xH2, Midpoint, 3) \
    X(spatium::Real50, "Real50", S2xH2, VerifyExpLog, 3) \
    X(spatium::Real50, "Real50", S2xS2, Derivative, 3) \
    X(spatium::Real50, "Real50", S2xS2, DerivedDistance, 3) \
    X(spatium::Real50, "Real50", S2xS2, ExpLog, 3) \
    X(spatium::Real50, "Real50", S2xS2, FrechetMean, 3) \
    X(spatium::Real50, "Real50", S2xS2, Infinity, 3) \
    X(spatium::Real50, "Real50", S2xS2, MetricAxioms, 3) \
    X(spatium::Real50, "Real50", S2xS2, Midpoint, 3) \
    X(spatium::Real50, "Real50", S2xS2, VerifyExpLog, 3) \
    X(spatium::Real50, "Real50", S3, Derivative, 3) \
    X(spatium::Real50, "Real50", S3, DerivedDistance, 3) \
    X(spatium::Real50, "Real50", S3, ExpLog, 3) \
    X(spatium::Real50, "Real50", S3, FrechetMean, 3) \
    X(spatium::Real50, "Real50", S3, Infinity, 3) \
    X(spatium::Real50, "Real50", S3, MetricAxioms, 3) \
    X(spatium::Real50, "Real50", S3, Midpoint, 3) \
    X(spatium::Real50, "Real50", S3, VerifyExpLog, 3) \
    X(spatium::Real50, "Real50", S4, Derivative, 3) \
    X(spatium::Real50, "Real50", S4, DerivedDistance, 3) \
    X(spatium::Real50, "Real50", S4, ExpLog, 3) \
    X(spatium::Real50, "Real50", S4, FrechetMean, 3) \
    X(spatium::Real50, "Real50", S4, Infinity, 3) \
    X(spatium::Real50, "Real50", S4, MetricAxioms, 3) \
    X(spatium::Real50, "Real50", S4, Midpoint, 3) \
    X(spatium::Real50, "Real50", S4, VerifyExpLog, 3) \
    X(spatium::Real50, "Real50", S7, Derivative, 3) \
    X(spatium::Real50, "Real50", S7, DerivedDistance, 3) \
    X(spatium::Real50, "Real50", S7, ExpLog, 3) \
    X(spatium::Real50, "Real50", S7, FrechetMean, 3) \
    X(spatium::Real50, "Real50", S7, Infinity, 3) \
    X(spatium::Real50, "Real50", S7, MetricAxioms, 3) \
    X(spatium::Real50, "Real50", S7, Midpoint, 3) \
    X(spatium::Real50, "Real50", S7, VerifyExpLog, 3) \
    X(spatium::Real50, "Real50", SPDAff, Derivative, 3) \
    X(spatium::Real50, "Real50", SPDAff, DerivedDistance, 3) \
    X(spatium::Real50, "Real50", SPDAff, ExpLog, 3) \
    X(spatium::Real50, "Real50", SPDAff, FrechetMean, 3) \
    X(spatium::Real50, "Real50", SPDAff, Infinity, 3) \
    X(spatium::Real50, "Real50", SPDAff, MetricAxioms, 3) \
    X(spatium::Real50, "Real50", SPDAff, Midpoint, 3) \
    X(spatium::Real50, "Real50", SPDAff, VerifyExpLog, 3) \
    X(spatium::Real50, "Real50", SPDAffxS2, Derivative, 3) \
    X(spatium::Real50, "Real50", SPDAffxS2, DerivedDistance, 3) \
    X(spatium::Real50, "Real50", SPDAffxS2, ExpLog, 3) \
    X(spatium::Real50, "Real50", SPDAffxS2, FrechetMean, 3) \
    X(spatium::Real50, "Real50", SPDAffxS2, Infinity, 3) \
    X(spatium::Real50, "Real50", SPDAffxS2, MetricAxioms, 3) \
    X(spatium::Real50, "Real50", SPDAffxS2, Midpoint, 3) \
    X(spatium::Real50, "Real50", SPDAffxS2, VerifyExpLog, 3) \
    X(spatium::Real50, "Real50", SPDLogE, Derivative, 3) \
    X(spatium::Real50, "Real50", SPDLogE, DerivedDistance, 3) \
    X(spatium::Real50, "Real50", SPDLogE, ExpLog, 3) \
    X(spatium::Real50, "Real50", SPDLogE, FrechetMean, 3) \
    X(spatium::Real50, "Real50", SPDLogE, Infinity, 3) \
    X(spatium::Real50, "Real50", SPDLogE, MetricAxioms, 3) \
    X(spatium::Real50, "Real50", SPDLogE, Midpoint, 3) \
    X(spatium::Real50, "Real50", SPDLogE, VerifyExpLog, 3) \
    X(spatium::Real50, "Real50", SPDLogExS2, Derivative, 3) \
    X(spatium::Real50, "Real50", SPDLogExS2, DerivedDistance, 3) \
    X(spatium::Real50, "Real50", SPDLogExS2, ExpLog, 3) \
    X(spatium::Real50, "Real50", SPDLogExS2, FrechetMean, 3) \
    X(spatium::Real50, "Real50", SPDLogExS2, Infinity, 3) \
    X(spatium::Real50, "Real50", SPDLogExS2, MetricAxioms, 3) \
    X(spatium::Real50, "Real50", SPDLogExS2, Midpoint, 3) \
    X(spatium::Real50, "Real50", SPDLogExS2, VerifyExpLog, 3) \
    X(spatium::Real50, "Real50", SphereLevelSet, Derivative, 3) \
    X(spatium::Real50, "Real50", SphereLevelSet, DerivedDistance, 1) \
    X(spatium::Real50, "Real50", SphereLevelSet, ExpLog, 1) \
    X(spatium::Real50, "Real50", SphereLevelSet, FrechetMean, 3) \
    X(spatium::Real50, "Real50", SphereLevelSet, Infinity, 3) \
    X(spatium::Real50, "Real50", SphereLevelSet, MetricAxioms, 3) \
    X(spatium::Real50, "Real50", SphereLevelSet, Midpoint, 1) \
    X(spatium::Real50, "Real50", SphereLevelSet, VerifyExpLog, 1) \
    X(spatium::Real50, "Real50", TorusChart, Derivative, 3) \
    X(spatium::Real50, "Real50", TorusChart, DerivedDistance, 1) \
    X(spatium::Real50, "Real50", TorusChart, ExpLog, 1) \
    X(spatium::Real50, "Real50", TorusChart, FrechetMean, 1) \
    X(spatium::Real50, "Real50", TorusChart, Infinity, 3) \
    X(spatium::Real50, "Real50", TorusChart, MetricAxioms, 3) \
    X(spatium::Real50, "Real50", TorusChart, Midpoint, 1) \
    X(spatium::Real50, "Real50", TorusChart, VerifyExpLog, 1) \

#else
#define CONNECTIVITY_CELLS_BOOST(X)
#endif

// Minutes each; run only with SPATIUM_CONNECTIVITY_HEAVY (the CI job regenerates them).
#if SPATIUM_HAS_BOOST_MULTIPRECISION
#define CONNECTIVITY_CELLS_HEAVY(X) \
    X(spatium::Real50, "Real50", H2Derived, Derivative, 3) \
    X(spatium::Real50, "Real50", H2Derived, DerivedDistance, 3) \
    X(spatium::Real50, "Real50", H2Derived, ExpLog, 3) \
    X(spatium::Real50, "Real50", H2Derived, FrechetMean, 3) \
    X(spatium::Real50, "Real50", H2Derived, Infinity, 3) \
    X(spatium::Real50, "Real50", H2Derived, MetricAxioms, 3) \
    X(spatium::Real50, "Real50", H2Derived, Midpoint, 3) \
    X(spatium::Real50, "Real50", H2Derived, VerifyExpLog, 3) \
    X(spatium::Real50, "Real50", H2DerivedxS2, Derivative, 3) \
    X(spatium::Real50, "Real50", H2DerivedxS2, DerivedDistance, 3) \
    X(spatium::Real50, "Real50", H2DerivedxS2, ExpLog, 3) \
    X(spatium::Real50, "Real50", H2DerivedxS2, FrechetMean, 3) \
    X(spatium::Real50, "Real50", H2DerivedxS2, Infinity, 3) \
    X(spatium::Real50, "Real50", H2DerivedxS2, MetricAxioms, 3) \
    X(spatium::Real50, "Real50", H2DerivedxS2, Midpoint, 3) \
    X(spatium::Real50, "Real50", H2DerivedxS2, VerifyExpLog, 3) \
    X(spatium::Real50, "Real50", S2Derived, Derivative, 3) \
    X(spatium::Real50, "Real50", S2Derived, DerivedDistance, 3) \
    X(spatium::Real50, "Real50", S2Derived, ExpLog, 3) \
    X(spatium::Real50, "Real50", S2Derived, FrechetMean, 3) \
    X(spatium::Real50, "Real50", S2Derived, Infinity, 3) \
    X(spatium::Real50, "Real50", S2Derived, MetricAxioms, 3) \
    X(spatium::Real50, "Real50", S2Derived, Midpoint, 3) \
    X(spatium::Real50, "Real50", S2Derived, VerifyExpLog, 3) \

#else
#define CONNECTIVITY_CELLS_HEAVY(X)
#endif
