#pragma once
// Generated by scripts/gen_connectivity.py -- do not edit; rerun it.
// The cells that compile, and the level each reached, for
// tests/test_connectivity.cpp. X(scalar type, scalar name, space, probe, level).
#define CONNECTIVITY_CELLS(X) \
    X(spatium::Dual<double>, "Dual", E3, Derivative, 3) \
    X(spatium::Dual<double>, "Dual", E3, DerivedDistance, 3) \
    X(spatium::Dual<double>, "Dual", E3, ExpLog, 3) \
    X(spatium::Dual<double>, "Dual", E3, FrechetMean, 3) \
    X(spatium::Dual<double>, "Dual", E3, MetricAxioms, 3) \
    X(spatium::Dual<double>, "Dual", E3, Midpoint, 3) \
    X(spatium::Dual<double>, "Dual", E3, VerifyExpLog, 3) \
    X(spatium::Dual<double>, "Dual", S2, Derivative, 3) \
    X(spatium::Dual<double>, "Dual", S2, DerivedDistance, 3) \
    X(spatium::Dual<double>, "Dual", S2, ExpLog, 3) \
    X(spatium::Dual<double>, "Dual", S2, FrechetMean, 3) \
    X(spatium::Dual<double>, "Dual", S2, MetricAxioms, 3) \
    X(spatium::Dual<double>, "Dual", S2, Midpoint, 3) \
    X(spatium::Dual<double>, "Dual", S2, VerifyExpLog, 3) \
    X(spatium::Dual<double>, "Dual", S2xE1, Derivative, 3) \
    X(spatium::Dual<double>, "Dual", S2xE1, DerivedDistance, 3) \
    X(spatium::Dual<double>, "Dual", S2xE1, ExpLog, 3) \
    X(spatium::Dual<double>, "Dual", S2xE1, FrechetMean, 3) \
    X(spatium::Dual<double>, "Dual", S2xE1, MetricAxioms, 3) \
    X(spatium::Dual<double>, "Dual", S2xE1, Midpoint, 3) \
    X(spatium::Dual<double>, "Dual", S2xE1, VerifyExpLog, 3) \
    X(spatium::Dual<double>, "Dual", SPDLogE, Derivative, 3) \
    X(spatium::Dual<double>, "Dual", SPDLogE, DerivedDistance, 3) \
    X(spatium::Dual<double>, "Dual", SPDLogE, ExpLog, 3) \
    X(spatium::Dual<double>, "Dual", SPDLogE, FrechetMean, 3) \
    X(spatium::Dual<double>, "Dual", SPDLogE, MetricAxioms, 3) \
    X(spatium::Dual<double>, "Dual", SPDLogE, Midpoint, 3) \
    X(spatium::Dual<double>, "Dual", SPDLogE, VerifyExpLog, 3) \
    X(spatium::Dual<spatium::Dual<double>>, "Dual2", E3, Derivative, 3) \
    X(spatium::Dual<spatium::Dual<double>>, "Dual2", E3, DerivedDistance, 3) \
    X(spatium::Dual<spatium::Dual<double>>, "Dual2", E3, ExpLog, 3) \
    X(spatium::Dual<spatium::Dual<double>>, "Dual2", E3, FrechetMean, 3) \
    X(spatium::Dual<spatium::Dual<double>>, "Dual2", E3, MetricAxioms, 3) \
    X(spatium::Dual<spatium::Dual<double>>, "Dual2", E3, Midpoint, 3) \
    X(spatium::Dual<spatium::Dual<double>>, "Dual2", E3, VerifyExpLog, 3) \
    X(spatium::Dual<spatium::Dual<double>>, "Dual2", S2, Derivative, 3) \
    X(spatium::Dual<spatium::Dual<double>>, "Dual2", S2, DerivedDistance, 3) \
    X(spatium::Dual<spatium::Dual<double>>, "Dual2", S2, ExpLog, 3) \
    X(spatium::Dual<spatium::Dual<double>>, "Dual2", S2, FrechetMean, 3) \
    X(spatium::Dual<spatium::Dual<double>>, "Dual2", S2, MetricAxioms, 3) \
    X(spatium::Dual<spatium::Dual<double>>, "Dual2", S2, Midpoint, 3) \
    X(spatium::Dual<spatium::Dual<double>>, "Dual2", S2, VerifyExpLog, 3) \
    X(spatium::Dual<spatium::Dual<double>>, "Dual2", S2xE1, Derivative, 3) \
    X(spatium::Dual<spatium::Dual<double>>, "Dual2", S2xE1, DerivedDistance, 3) \
    X(spatium::Dual<spatium::Dual<double>>, "Dual2", S2xE1, ExpLog, 3) \
    X(spatium::Dual<spatium::Dual<double>>, "Dual2", S2xE1, FrechetMean, 3) \
    X(spatium::Dual<spatium::Dual<double>>, "Dual2", S2xE1, MetricAxioms, 3) \
    X(spatium::Dual<spatium::Dual<double>>, "Dual2", S2xE1, Midpoint, 3) \
    X(spatium::Dual<spatium::Dual<double>>, "Dual2", S2xE1, VerifyExpLog, 3) \
    X(spatium::Dual<spatium::Dual<double>>, "Dual2", SPDLogE, Derivative, 3) \
    X(spatium::Dual<spatium::Dual<double>>, "Dual2", SPDLogE, DerivedDistance, 3) \
    X(spatium::Dual<spatium::Dual<double>>, "Dual2", SPDLogE, ExpLog, 3) \
    X(spatium::Dual<spatium::Dual<double>>, "Dual2", SPDLogE, FrechetMean, 3) \
    X(spatium::Dual<spatium::Dual<double>>, "Dual2", SPDLogE, MetricAxioms, 3) \
    X(spatium::Dual<spatium::Dual<double>>, "Dual2", SPDLogE, Midpoint, 3) \
    X(spatium::Dual<spatium::Dual<double>>, "Dual2", SPDLogE, VerifyExpLog, 3) \
    X(double, "double", E3, Derivative, 3) \
    X(double, "double", E3, DerivedDistance, 3) \
    X(double, "double", E3, ExpLog, 3) \
    X(double, "double", E3, FrechetMean, 3) \
    X(double, "double", E3, MetricAxioms, 3) \
    X(double, "double", E3, Midpoint, 3) \
    X(double, "double", E3, VerifyExpLog, 3) \
    X(double, "double", H2, Derivative, 3) \
    X(double, "double", H2, DerivedDistance, 3) \
    X(double, "double", H2, ExpLog, 3) \
    X(double, "double", H2, FrechetMean, 3) \
    X(double, "double", H2, MetricAxioms, 3) \
    X(double, "double", H2, Midpoint, 3) \
    X(double, "double", H2, VerifyExpLog, 3) \
    X(double, "double", S2, Derivative, 3) \
    X(double, "double", S2, DerivedDistance, 3) \
    X(double, "double", S2, ExpLog, 3) \
    X(double, "double", S2, FrechetMean, 3) \
    X(double, "double", S2, MetricAxioms, 3) \
    X(double, "double", S2, Midpoint, 3) \
    X(double, "double", S2, VerifyExpLog, 3) \
    X(double, "double", S2xE1, Derivative, 3) \
    X(double, "double", S2xE1, DerivedDistance, 3) \
    X(double, "double", S2xE1, ExpLog, 3) \
    X(double, "double", S2xE1, FrechetMean, 3) \
    X(double, "double", S2xE1, MetricAxioms, 3) \
    X(double, "double", S2xE1, Midpoint, 3) \
    X(double, "double", S2xE1, VerifyExpLog, 3) \
    X(double, "double", SPDAff, Derivative, 2) \
    X(double, "double", SPDAff, DerivedDistance, 2) \
    X(double, "double", SPDAff, ExpLog, 2) \
    X(double, "double", SPDAff, FrechetMean, 2) \
    X(double, "double", SPDAff, MetricAxioms, 2) \
    X(double, "double", SPDAff, Midpoint, 2) \
    X(double, "double", SPDAff, VerifyExpLog, 2) \
    X(double, "double", SPDLogE, Derivative, 3) \
    X(double, "double", SPDLogE, DerivedDistance, 3) \
    X(double, "double", SPDLogE, ExpLog, 3) \
    X(double, "double", SPDLogE, FrechetMean, 3) \
    X(double, "double", SPDLogE, MetricAxioms, 3) \
    X(double, "double", SPDLogE, Midpoint, 3) \
    X(double, "double", SPDLogE, VerifyExpLog, 3) \
    X(double, "double", SphereLevelSet, Derivative, 2) \
    X(double, "double", SphereLevelSet, MetricAxioms, 2) \
    X(double, "double", TorusChart, Derivative, 2) \
    X(double, "double", TorusChart, MetricAxioms, 2) \
    X(float, "float", E3, Derivative, 3) \
    X(float, "float", E3, DerivedDistance, 3) \
    X(float, "float", E3, ExpLog, 3) \
    X(float, "float", E3, FrechetMean, 3) \
    X(float, "float", E3, MetricAxioms, 3) \
    X(float, "float", E3, Midpoint, 3) \
    X(float, "float", E3, VerifyExpLog, 3) \
    X(float, "float", H2, Derivative, 3) \
    X(float, "float", H2, DerivedDistance, 3) \
    X(float, "float", H2, ExpLog, 3) \
    X(float, "float", H2, FrechetMean, 3) \
    X(float, "float", H2, MetricAxioms, 3) \
    X(float, "float", H2, Midpoint, 3) \
    X(float, "float", H2, VerifyExpLog, 3) \
    X(float, "float", S2, Derivative, 3) \
    X(float, "float", S2, DerivedDistance, 3) \
    X(float, "float", S2, ExpLog, 3) \
    X(float, "float", S2, FrechetMean, 3) \
    X(float, "float", S2, MetricAxioms, 3) \
    X(float, "float", S2, Midpoint, 3) \
    X(float, "float", S2, VerifyExpLog, 3) \
    X(float, "float", S2xE1, Derivative, 3) \
    X(float, "float", S2xE1, DerivedDistance, 3) \
    X(float, "float", S2xE1, ExpLog, 3) \
    X(float, "float", S2xE1, FrechetMean, 3) \
    X(float, "float", S2xE1, MetricAxioms, 3) \
    X(float, "float", S2xE1, Midpoint, 3) \
    X(float, "float", S2xE1, VerifyExpLog, 3) \
    X(float, "float", SPDAff, Derivative, 3) \
    X(float, "float", SPDAff, DerivedDistance, 3) \
    X(float, "float", SPDAff, ExpLog, 3) \
    X(float, "float", SPDAff, FrechetMean, 3) \
    X(float, "float", SPDAff, MetricAxioms, 3) \
    X(float, "float", SPDAff, Midpoint, 3) \
    X(float, "float", SPDAff, VerifyExpLog, 3) \
    X(float, "float", SPDLogE, Derivative, 3) \
    X(float, "float", SPDLogE, DerivedDistance, 3) \
    X(float, "float", SPDLogE, ExpLog, 3) \
    X(float, "float", SPDLogE, FrechetMean, 3) \
    X(float, "float", SPDLogE, MetricAxioms, 3) \
    X(float, "float", SPDLogE, Midpoint, 3) \
    X(float, "float", SPDLogE, VerifyExpLog, 3) \
    X(float, "float", SphereLevelSet, Derivative, 3) \
    X(float, "float", SphereLevelSet, MetricAxioms, 3) \
    X(float, "float", TorusChart, Derivative, 3) \
    X(float, "float", TorusChart, MetricAxioms, 3) \
    X(long double, "long double", E3, Derivative, 3) \
    X(long double, "long double", E3, DerivedDistance, 3) \
    X(long double, "long double", E3, ExpLog, 3) \
    X(long double, "long double", E3, FrechetMean, 3) \
    X(long double, "long double", E3, MetricAxioms, 3) \
    X(long double, "long double", E3, Midpoint, 3) \
    X(long double, "long double", E3, VerifyExpLog, 3) \
    X(long double, "long double", H2, Derivative, 3) \
    X(long double, "long double", H2, DerivedDistance, 3) \
    X(long double, "long double", H2, ExpLog, 3) \
    X(long double, "long double", H2, FrechetMean, 3) \
    X(long double, "long double", H2, MetricAxioms, 3) \
    X(long double, "long double", H2, Midpoint, 3) \
    X(long double, "long double", H2, VerifyExpLog, 3) \
    X(long double, "long double", S2, Derivative, 3) \
    X(long double, "long double", S2, DerivedDistance, 3) \
    X(long double, "long double", S2, ExpLog, 3) \
    X(long double, "long double", S2, FrechetMean, 3) \
    X(long double, "long double", S2, MetricAxioms, 3) \
    X(long double, "long double", S2, Midpoint, 3) \
    X(long double, "long double", S2, VerifyExpLog, 3) \
    X(long double, "long double", S2xE1, Derivative, 3) \
    X(long double, "long double", S2xE1, DerivedDistance, 3) \
    X(long double, "long double", S2xE1, ExpLog, 3) \
    X(long double, "long double", S2xE1, FrechetMean, 3) \
    X(long double, "long double", S2xE1, MetricAxioms, 3) \
    X(long double, "long double", S2xE1, Midpoint, 3) \
    X(long double, "long double", S2xE1, VerifyExpLog, 3) \
    X(long double, "long double", SPDAff, Derivative, 3) \
    X(long double, "long double", SPDAff, DerivedDistance, 3) \
    X(long double, "long double", SPDAff, ExpLog, 3) \
    X(long double, "long double", SPDAff, FrechetMean, 3) \
    X(long double, "long double", SPDAff, MetricAxioms, 3) \
    X(long double, "long double", SPDAff, Midpoint, 3) \
    X(long double, "long double", SPDAff, VerifyExpLog, 3) \
    X(long double, "long double", SPDLogE, Derivative, 3) \
    X(long double, "long double", SPDLogE, DerivedDistance, 3) \
    X(long double, "long double", SPDLogE, ExpLog, 3) \
    X(long double, "long double", SPDLogE, FrechetMean, 3) \
    X(long double, "long double", SPDLogE, MetricAxioms, 3) \
    X(long double, "long double", SPDLogE, Midpoint, 3) \
    X(long double, "long double", SPDLogE, VerifyExpLog, 3) \
    X(long double, "long double", SphereLevelSet, Derivative, 3) \
    X(long double, "long double", SphereLevelSet, MetricAxioms, 3) \
    X(long double, "long double", TorusChart, Derivative, 3) \
    X(long double, "long double", TorusChart, MetricAxioms, 3) \
    CONNECTIVITY_CELLS_BOOST(X)

#if SPATIUM_HAS_BOOST_MULTIPRECISION
#define CONNECTIVITY_CELLS_BOOST(X) \
    X(spatium::Real50, "Real50", E3, Derivative, 3) \
    X(spatium::Real50, "Real50", E3, DerivedDistance, 3) \
    X(spatium::Real50, "Real50", E3, ExpLog, 3) \
    X(spatium::Real50, "Real50", E3, FrechetMean, 3) \
    X(spatium::Real50, "Real50", E3, MetricAxioms, 3) \
    X(spatium::Real50, "Real50", E3, Midpoint, 3) \
    X(spatium::Real50, "Real50", E3, VerifyExpLog, 3) \
    X(spatium::Real50, "Real50", H2, Derivative, 3) \
    X(spatium::Real50, "Real50", H2, DerivedDistance, 3) \
    X(spatium::Real50, "Real50", H2, ExpLog, 3) \
    X(spatium::Real50, "Real50", H2, FrechetMean, 3) \
    X(spatium::Real50, "Real50", H2, MetricAxioms, 3) \
    X(spatium::Real50, "Real50", H2, Midpoint, 3) \
    X(spatium::Real50, "Real50", H2, VerifyExpLog, 3) \
    X(spatium::Real50, "Real50", S2, Derivative, 3) \
    X(spatium::Real50, "Real50", S2, DerivedDistance, 3) \
    X(spatium::Real50, "Real50", S2, ExpLog, 3) \
    X(spatium::Real50, "Real50", S2, FrechetMean, 3) \
    X(spatium::Real50, "Real50", S2, MetricAxioms, 3) \
    X(spatium::Real50, "Real50", S2, Midpoint, 3) \
    X(spatium::Real50, "Real50", S2, VerifyExpLog, 3) \
    X(spatium::Real50, "Real50", S2xE1, Derivative, 3) \
    X(spatium::Real50, "Real50", S2xE1, DerivedDistance, 3) \
    X(spatium::Real50, "Real50", S2xE1, ExpLog, 3) \
    X(spatium::Real50, "Real50", S2xE1, FrechetMean, 3) \
    X(spatium::Real50, "Real50", S2xE1, MetricAxioms, 3) \
    X(spatium::Real50, "Real50", S2xE1, Midpoint, 3) \
    X(spatium::Real50, "Real50", S2xE1, VerifyExpLog, 3) \
    X(spatium::Real50, "Real50", SPDLogE, Derivative, 3) \
    X(spatium::Real50, "Real50", SPDLogE, DerivedDistance, 3) \
    X(spatium::Real50, "Real50", SPDLogE, ExpLog, 3) \
    X(spatium::Real50, "Real50", SPDLogE, FrechetMean, 3) \
    X(spatium::Real50, "Real50", SPDLogE, MetricAxioms, 3) \
    X(spatium::Real50, "Real50", SPDLogE, Midpoint, 3) \
    X(spatium::Real50, "Real50", SPDLogE, VerifyExpLog, 3) \

#else
#define CONNECTIVITY_CELLS_BOOST(X)
#endif
