#!/usr/bin/env python3
"""Check that every source file named in the docs actually exists.

This exists because of the class of staleness found by hand 2026-09-15:
`docs/concept-driven-physics.md` §4.2 listed `test_block_b_finish.cpp`,
`test_block_c_close.cpp` and `test_block_d_start.cpp` as the tests
covering three sections of the physics work. None of the three had
existed for three weeks -- they were the "Block A/B/C/D" milestone names
that an earlier pass reports having stripped, surviving as *file names*,
which read as a checkable reference and were not.

The point worth generalising from that find: the document's *ideas* were
all still correct. What rotted was exclusively the parts a reader could
check -- a file name, a test count, a line count. Those are facts about
the tree, and a document that types them by hand is promising to retype
them every time the tree moves. This script keeps that promise for the
file names, mechanically, instead of relying on the next person (or
agent) to notice by hand.

What it checks: every token in the documentation that looks like one of
our source files (a known extension, optionally with a directory prefix)
names a file that exists somewhere in the tree. Matching is by basename,
so a doc may write `build.hpp` or `include/spatium/io/build.hpp` and
both resolve.

What it does NOT check, deliberately:

  * that the description beside the name is accurate. Narrower and
    cheaper than that, on purpose -- same call as
    check_claude_md_layout.py.
  * the reverse direction. A doc claiming a file was *removed* when it
    still exists is the other half of this failure class (ROADMAP's
    audit entry said exactly that about cloth_sphere_probe.cpp, found in
    the same pass), and it is not mechanically checkable: "removed" is
    prose, not a reference. It stays a human job.
  * counts. A test or LOC count is derivable too, but the honest fix
    there is to stop writing the number down, which is what §4.2 now
    does, rather than to check it on every commit.

A name may be legitimately absent for four reasons, and each one has to
be written down in NOT_IN_TREE below with which reason it is: the doc
records a deletion and has to name the deleted thing; the doc proposes a
file that is not written yet; the file is generated at build time; or it
belongs to another project. Writing the reason next to the name is the
point -- "this file does not exist" is then a stated fact rather than an
accident, which is the whole difference this script is trying to make.
"""
import re
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent

# Documentation that gets checked. Everything a reader is pointed at.
DOC_GLOBS = ["docs/*.md", "README.md", "CONTRIBUTING.md", "CLAUDE.md", "rsc/README.md"]

# Extensions that name something in this tree rather than a concept.
# `.dot` is deliberately absent: `n.dot(u)` in a code sample is a vector
# operation, and the one real .dot file (docs/dependency-graph.dot) is
# already covered by gen_dependency_graph.py --check.
EXTENSIONS = {".cpp", ".hpp", ".cu", ".cuh", ".cppm", ".py", ".md"}

# Directories that hold build output or vendored third-party code, whose
# contents must not satisfy a reference from our own docs.
SKIP_DIRS = {".git", ".direnv", "result", "vendor"}

# Names the docs may use without a file behind them, each with its reason.
NOT_IN_TREE = {
    # -- the doc records a deletion, so it has to name the deleted thing
    "CHANGELOG.md": "deleted by the 2026-08-26 audit; the entry naming it records the deletion",
    "test_block_b_finish.cpp": "never existed; ROADMAP's correction entry names it to say so",
    "test_block_c_close.cpp": "never existed; ROADMAP's correction entry names it to say so",
    "test_block_d_start.cpp": "never existed; ROADMAP's correction entry names it to say so",
    "table.cpp": "never existed; ROADMAP's corrected table-renderer entry names the old wrong path",
    # -- proposed, not written yet
    "build_json.hpp": "proposed in ROADMAP as the first consumer of function names; not written",
    # -- generated at build time, so it only ever exists inside a build dir
    "build_info.hpp": "generated by the top-level CMakeLists.txt into the build directory",
    "embedded_base_data.hpp": "generated into the build directory by RSC's embedding step",
    # -- another project's tree
    "micro_wkv.py": "lives in the noesis repository, not this one",
}


def real_files() -> dict[str, list[Path]]:
    """Every file in the tree, indexed by basename."""
    index: dict[str, list[Path]] = {}
    for path in ROOT.rglob("*"):
        if not path.is_file():
            continue
        rel = path.relative_to(ROOT)
        if rel.parts[0].startswith("build") or rel.parts[0] in SKIP_DIRS:
            continue
        index.setdefault(path.name, []).append(rel)
    return index


# A path-ish token: optional directory parts, then a name with a known
# extension. Anchored so `foo.cpp` inside `my_foo.cpp` doesn't match, and
# so a glob is skipped whole rather than matched from after its `*` --
# `examples/cloth_*_demo.cpp` is a pattern, and there is nothing to
# resolve it against.
TOKEN = re.compile(
    r"(?<![\w./*?-])((?:[\w.-]+/)*[\w.-]+(?:" + "|".join(re.escape(e) for e in EXTENSIONS) + r"))(?![\w])"
)


def referenced(doc: Path) -> set[tuple[str, int]]:
    """Every file-looking token in a document, with its line number."""
    out: set[tuple[str, int]] = set()
    for lineno, line in enumerate(doc.read_text(encoding="utf-8").splitlines(), 1):
        for match in TOKEN.finditer(line):
            token = match.group(1)
            # A URL path is someone else's tree, not ours.
            if "://" in line[: match.start()].rsplit(" ", 1)[-1]:
                continue
            out.add((token, lineno))
    return out


def main() -> int:
    index = real_files()
    problems: list[str] = []

    docs = sorted({p for g in DOC_GLOBS for p in ROOT.glob(g)})
    checked = 0

    for doc in docs:
        for token, lineno in sorted(referenced(doc)):
            name = token.rsplit("/", 1)[-1]
            checked += 1
            if name in NOT_IN_TREE:
                continue
            if name not in index:
                problems.append(
                    f"{doc.relative_to(ROOT)}:{lineno}: names `{token}`, which does not exist"
                )

    if problems:
        print("Documentation names files that are not in the tree:\n", file=sys.stderr)
        for p in problems:
            print(f"  {p}", file=sys.stderr)
        print(
            "\nEither the file was renamed and the doc still says the old name, or the\n"
            "doc describes something that was never written. If the doc means to name a\n"
            "file that has no counterpart in the tree -- one it records as deleted, one\n"
            "it only proposes, one generated at build time, or one belonging to another\n"
            "project -- add it to NOT_IN_TREE in scripts/check_doc_file_refs.py with\n"
            "which of those it is.",
            file=sys.stderr,
        )
        return 1

    print(f"All {checked} file references across {len(docs)} documents resolve.")
    return 0


if __name__ == "__main__":
    sys.exit(main())
